/*
 * mc_configuration's byte stream - the reference's own, not the port's invention.
 *
 * confgenerator_serialize_mcconf() / confgenerator_deserialize_mcconf() are autogenerated
 * from the configuration's field list; this port gets the same thing from
 * tools/gen_mcconf_from_reference.py, which reads the reference tree and emits
 * motor_config/mcconf_manifest.h. Everything below expands MCCONF_WIRE(X) from that
 * manifest, so the writer, the reader and the defaults are one list and cannot drift
 * apart. MCCONF_WIRE_LEN is asserted to be the reference's 488 bytes, and the golden test
 * compares this output byte for byte against the reference's own serialiser.
 *
 * The reference's stream has no version, length or CRC of its own - just the signature
 * and the fields. There is no envelope here either: the stored configuration is the
 * variable table motor_config keeps, not an image this file frames.
 */
#include "appconf_defaults.h"
#include "mcconf_defaults.h"
#include "motor_config/appconf_manifest.h"
#include "motor_config/mcconf_manifest.h"
#include "motor_config/motor_config.h"
#include <math.h>
#include <string.h>

/*
 * The reference's own byte encodings (util/buffer.c), implemented here rather than
 * pulled from infra/vesc_buffer: an app may not depend on infra, which is the same
 * reason app/vesc_comm carries its own copies. test_motor_config cross-checks these
 * against infra/vesc_buffer so the two cannot drift, and the golden test pins the whole
 * stream against the reference serialiser's output.
 *
 * float32_auto is not variable length: it is the IEEE-754 single-precision bit pattern,
 * rebuilt through frexpf, with subnormals zeroed. float16 is int16 big-endian of
 * value * scale. Neither is the fixed-point int32 this file used before.
 */
static void buffer_append_uint16(uint8_t *buffer, uint16_t number, int32_t *index) {
    buffer[(*index)++] = (uint8_t)(number >> 8);
    buffer[(*index)++] = (uint8_t)number;
}

static void buffer_append_uint32(uint8_t *buffer, uint32_t number, int32_t *index) {
    buffer[(*index)++] = (uint8_t)(number >> 24);
    buffer[(*index)++] = (uint8_t)(number >> 16);
    buffer[(*index)++] = (uint8_t)(number >> 8);
    buffer[(*index)++] = (uint8_t)number;
}

static void buffer_append_int32(uint8_t *buffer, int32_t number, int32_t *index) {
    buffer_append_uint32(buffer, (uint32_t)number, index);
}

static void buffer_append_float16(uint8_t *buffer, float number, float scale, int32_t *index) {
    buffer_append_uint16(buffer, (uint16_t)(int16_t)(number * scale), index);
}

static void buffer_append_float32_auto(uint8_t *buffer, float number, int32_t *index) {
    if (fabsf(number) < 1.5e-38f) {
        number = 0.0f;
    }

    int e = 0;
    float sig = frexpf(number, &e);
    float sig_abs = fabsf(sig);
    uint32_t sig_i = 0u;

    if (sig_abs >= 0.5f) {
        sig_i = (uint32_t)((sig_abs - 0.5f) * 2.0f * 8388608.0f);
        e += 126;
    }

    uint32_t res = ((uint32_t)(e & 0xFF) << 23) | (sig_i & 0x7FFFFFu);
    if (sig < 0.0f) {
        res |= 1u << 31;
    }

    buffer_append_uint32(buffer, res, index);
}

static int16_t buffer_get_int16(const uint8_t *buffer, int32_t *index) {
    int16_t res = (int16_t)(((uint16_t)buffer[*index] << 8) | (uint16_t)buffer[*index + 1]);
    *index += 2;
    return res;
}

static uint16_t buffer_get_uint16(const uint8_t *buffer, int32_t *index) {
    uint16_t res = (uint16_t)(((uint16_t)buffer[*index] << 8) | (uint16_t)buffer[*index + 1]);
    *index += 2;
    return res;
}

static uint32_t buffer_get_uint32(const uint8_t *buffer, int32_t *index) {
    uint32_t res = ((uint32_t)buffer[*index] << 24) | ((uint32_t)buffer[*index + 1] << 16) |
                   ((uint32_t)buffer[*index + 2] << 8) | (uint32_t)buffer[*index + 3];
    *index += 4;
    return res;
}

static int32_t buffer_get_int32(const uint8_t *buffer, int32_t *index) {
    return (int32_t)buffer_get_uint32(buffer, index);
}

static float buffer_get_float16(const uint8_t *buffer, float scale, int32_t *index) {
    return (float)buffer_get_int16(buffer, index) / scale;
}

/*
 * The reference's reader, arithmetic included: the mantissa is rebuilt in double
 * precision and scaled with ldexpf, not powf, and an all-zero encoding short-circuits to
 * zero rather than to 0.5 * 2^-126. Both matter for bit-exactness on real values.
 */
static float buffer_get_float32_auto(const uint8_t *buffer, int32_t *index) {
    uint32_t res = buffer_get_uint32(buffer, index);

    int e = (int)((res >> 23) & 0xFFu);
    uint32_t sig_i = res & 0x7FFFFFu;
    bool neg = (res & (1u << 31)) != 0u;

    float sig = 0.0f;
    if (e != 0 || sig_i != 0u) {
        sig = (float)sig_i / (8388608.0 * 2.0) + 0.5f;
        e -= 126;
    }

    if (neg) {
        sig = -sig;
    }

    return ldexpf(sig, e);
}

#define MCCONF_WRITE(kind, expr, scale, def) MCCONF_WRITE_##kind(expr, scale)
#define MCCONF_WRITE_U8(expr, scale) buffer[idx++] = (uint8_t)mcconf->expr;
#define MCCONF_WRITE_U16(expr, scale) buffer_append_uint16(buffer, mcconf->expr, &idx);
#define MCCONF_WRITE_U32(expr, scale) buffer_append_uint32(buffer, mcconf->expr, &idx);
#define MCCONF_WRITE_I32(expr, scale) buffer_append_int32(buffer, mcconf->expr, &idx);
#define MCCONF_WRITE_F16(expr, scale) buffer_append_float16(buffer, mcconf->expr, scale, &idx);
#define MCCONF_WRITE_F32A(expr, scale) buffer_append_float32_auto(buffer, mcconf->expr, &idx);
#define MCCONF_WRITE_NONE(expr, scale)

#define MCCONF_READ(kind, expr, scale, def) MCCONF_READ_##kind(expr, scale)
#define MCCONF_READ_U8(expr, scale) mcconf->expr = buffer[idx++];
#define MCCONF_READ_U16(expr, scale) mcconf->expr = buffer_get_uint16(buffer, &idx);
#define MCCONF_READ_U32(expr, scale) mcconf->expr = buffer_get_uint32(buffer, &idx);
#define MCCONF_READ_I32(expr, scale) mcconf->expr = buffer_get_int32(buffer, &idx);
#define MCCONF_READ_F16(expr, scale) mcconf->expr = buffer_get_float16(buffer, scale, &idx);
#define MCCONF_READ_F32A(expr, scale) mcconf->expr = buffer_get_float32_auto(buffer, &idx);
#define MCCONF_READ_NONE(expr, scale)

#define MCCONF_SET_DEFAULT(kind, expr, scale, def) MCCONF_SET_DEFAULT_##kind(expr, scale, def)
#define MCCONF_SET_DEFAULT_U8(expr, scale, def) mcconf->expr = (def);
#define MCCONF_SET_DEFAULT_U16(expr, scale, def) mcconf->expr = (def);
#define MCCONF_SET_DEFAULT_U32(expr, scale, def) mcconf->expr = (def);
#define MCCONF_SET_DEFAULT_I32(expr, scale, def) mcconf->expr = (def);
#define MCCONF_SET_DEFAULT_F16(expr, scale, def) mcconf->expr = (def);
#define MCCONF_SET_DEFAULT_F32(expr, scale, def) mcconf->expr = (def);
#define MCCONF_SET_DEFAULT_F32A(expr, scale, def) mcconf->expr = (def);
#define MCCONF_SET_DEFAULT_NONE(expr, scale, def) mcconf->expr = (def);

/*
 * The app configuration stream, the reference's confgenerator_serialize_appconf(): the
 * same kinds and the same three expansions as the mc stream above, against appconf.
 */
#define APPCONF_WRITE(kind, expr, scale, def) APPCONF_WRITE_##kind(expr, scale)
#define APPCONF_WRITE_U8(expr, scale) buffer[idx++] = (uint8_t)appconf->expr;
#define APPCONF_WRITE_U16(expr, scale) buffer_append_uint16(buffer, appconf->expr, &idx);
#define APPCONF_WRITE_U32(expr, scale) buffer_append_uint32(buffer, appconf->expr, &idx);
#define APPCONF_WRITE_I32(expr, scale) buffer_append_int32(buffer, appconf->expr, &idx);
#define APPCONF_WRITE_F16(expr, scale) buffer_append_float16(buffer, appconf->expr, scale, &idx);
#define APPCONF_WRITE_F32A(expr, scale) buffer_append_float32_auto(buffer, appconf->expr, &idx);
#define APPCONF_WRITE_NONE(expr, scale)

#define APPCONF_READ(kind, expr, scale, def) APPCONF_READ_##kind(expr, scale)
#define APPCONF_READ_U8(expr, scale) appconf->expr = buffer[idx++];
#define APPCONF_READ_U16(expr, scale) appconf->expr = buffer_get_uint16(buffer, &idx);
#define APPCONF_READ_U32(expr, scale) appconf->expr = buffer_get_uint32(buffer, &idx);
#define APPCONF_READ_I32(expr, scale) appconf->expr = buffer_get_int32(buffer, &idx);
#define APPCONF_READ_F16(expr, scale) appconf->expr = buffer_get_float16(buffer, scale, &idx);
#define APPCONF_READ_F32A(expr, scale) appconf->expr = buffer_get_float32_auto(buffer, &idx);
#define APPCONF_READ_NONE(expr, scale)

#define APPCONF_SET_DEFAULT(kind, expr, scale, def) APPCONF_SET_DEFAULT_##kind(expr, scale, def)
#define APPCONF_SET_DEFAULT_U8(expr, scale, def) appconf->expr = (def);
#define APPCONF_SET_DEFAULT_U16(expr, scale, def) appconf->expr = (def);
#define APPCONF_SET_DEFAULT_U32(expr, scale, def) appconf->expr = (def);
#define APPCONF_SET_DEFAULT_I32(expr, scale, def) appconf->expr = (def);
#define APPCONF_SET_DEFAULT_F16(expr, scale, def) appconf->expr = (def);
#define APPCONF_SET_DEFAULT_F32(expr, scale, def) appconf->expr = (def);
#define APPCONF_SET_DEFAULT_F32A(expr, scale, def) appconf->expr = (def);
#define APPCONF_SET_DEFAULT_NONE(expr, scale, def) appconf->expr = (def);

size_t motor_config_app_stream_len(void) {
    return (size_t)APPCONF_WIRE_LEN;
}

edge_status_t motor_config_serialize_app(const app_configuration_t *appconf, uint8_t *buffer,
                                         size_t buf_size, size_t *out_len) {
    if (appconf == (void *)0 || buffer == (void *)0 || out_len == (void *)0) {
        return EDGE_EINVAL;
    }
    if (buf_size < (size_t)APPCONF_WIRE_LEN) {
        return EDGE_ENOSPC;
    }

    int32_t idx = 0;
    buffer_append_uint32(buffer, APPCONF_SIGNATURE, &idx);
    APPCONF_WIRE(APPCONF_WRITE)

    *out_len = (size_t)idx;
    return EDGE_OK;
}

edge_status_t motor_config_deserialize_app(app_configuration_t *appconf, const uint8_t *buffer,
                                           size_t len) {
    if (appconf == (void *)0 || buffer == (void *)0) {
        return EDGE_EINVAL;
    }
    if (len < (size_t)APPCONF_WIRE_LEN) {
        return EDGE_EINVAL;
    }

    int32_t idx = 0;
    if (buffer_get_uint32(buffer, &idx) != APPCONF_SIGNATURE) {
        return EDGE_EINVAL;
    }
    APPCONF_WIRE(APPCONF_READ)

    return EDGE_OK;
}

void motor_config_set_defaults(mc_configuration_t *mcconf, app_configuration_t *appconf) {
    if (mcconf != (void *)0) {
        /*
         * Every value is the reference's own, straight out of
         * confgenerator_set_defaults_mcconf() via the manifest, and the macros in
         * mcconf_defaults.h carry the line they came from in mcconf_default.h. Six of
         * them used to be invented here (input current limits, motor inductance and flux
         * linkage, observer gain, current-loop integral gain); a default-configured motor
         * runs the observer and the current loop off those numbers.
         */
        memset(mcconf, 0, sizeof(*mcconf));
        MCCONF_WIRE(MCCONF_SET_DEFAULT)
    }
    if (appconf != (void *)0) {
        memset(appconf, 0, sizeof(*appconf));
        APPCONF_WIRE(APPCONF_SET_DEFAULT)
    }
}

edge_status_t motor_config_validate(const mc_configuration_t *mcconf,
                                    const app_configuration_t *appconf) {
    if (mcconf == (void *)0 || appconf == (void *)0) {
        return EDGE_EINVAL;
    }

    /*
     * This port's own guard, not the reference's: the reference loads whatever is stored
     * and lets the motor misbehave, while these ranges are the ones a wrong value cannot
     * come back from. It is deliberately not part of the byte stream, so a peer's
     * configuration that fails it is reported rather than silently rewritten.
     */
    if (mcconf->l_current_max <= 0.0f || mcconf->l_current_min >= 0.0f) {
        return EDGE_EINVAL;
    }
    if (mcconf->l_max_vin <= mcconf->l_min_vin || mcconf->l_min_vin <= 0.0f) {
        return EDGE_EINVAL;
    }
    if (mcconf->foc_f_zv < 5000.0f || mcconf->foc_f_zv > 100000.0f) {
        return EDGE_EINVAL;
    }
    if (appconf->timeout_msec == 0) {
        return EDGE_EINVAL;
    }
    if (mcconf->si_motor_poles < 2u || (mcconf->si_motor_poles % 2u) != 0u) {
        return EDGE_EINVAL;
    }
    if (mcconf->si_gear_ratio == 0.0f) {
        return EDGE_EINVAL;
    }
    if (mcconf->l_max_duty <= 0.0f || mcconf->l_max_duty > 1.0f) {
        return EDGE_EINVAL;
    }
    if (mcconf->foc_current_filter_const < 0.0f || mcconf->foc_current_filter_const > 1.0f) {
        return EDGE_EINVAL;
    }
    if (mcconf->foc_observer_type > 6u) { /* FOC_OBSERVER_MXV_LAMBDA_COMP_LIN */
        return EDGE_EINVAL;
    }
    if (mcconf->foc_sat_comp_mode > 3u) { /* SAT_COMP_LAMBDA_AND_FACTOR */
        return EDGE_EINVAL;
    }
    if (mcconf->foc_sat_comp < 0.0f) {
        return EDGE_EINVAL;
    }
    if (mcconf->cc_min_current < 0.0f) {
        return EDGE_EINVAL;
    }

    return EDGE_OK;
}

size_t motor_config_stream_len(void) {
    return (size_t)MCCONF_WIRE_LEN;
}

edge_status_t motor_config_serialize_mc(const mc_configuration_t *mcconf, uint8_t *buffer,
                                        size_t buf_size, size_t *out_len) {
    if (mcconf == (void *)0 || buffer == (void *)0 || out_len == (void *)0) {
        return EDGE_EINVAL;
    }
    if (buf_size < (size_t)MCCONF_WIRE_LEN) {
        return EDGE_ENOSPC;
    }

    int32_t idx = 0;
    buffer_append_uint32(buffer, MCCONF_SIGNATURE, &idx);
    MCCONF_WIRE(MCCONF_WRITE)

    *out_len = (size_t)idx;
    return EDGE_OK;
}

edge_status_t motor_config_deserialize_mc(mc_configuration_t *mcconf, const uint8_t *buffer,
                                          size_t len) {
    if (mcconf == (void *)0 || buffer == (void *)0) {
        return EDGE_EINVAL;
    }
    if (len < (size_t)MCCONF_WIRE_LEN) {
        return EDGE_EINVAL;
    }

    int32_t idx = 0;
    if (buffer_get_uint32(buffer, &idx) != MCCONF_SIGNATURE) {
        return EDGE_EINVAL;
    }
    MCCONF_WIRE(MCCONF_READ)

    return EDGE_OK;
}
