#ifndef EDGE_EVENTS_H
#define EDGE_EVENTS_H

#define EDGE_EVT_FRAMEWORK_BASE 0x0000u
#define EDGE_EVT_BOARD_BASE 0x0100u
#define EDGE_EVT_DLT645_BASE 0x1000u
#define EDGE_EVT_DLMS_BASE 0x1100u
#define EDGE_EVT_RELAY_BASE 0x1200u
#define EDGE_EVT_MODBUS_BASE 0x1300u
#define EDGE_EVT_PULSE_BASE 0x1500u
#define EDGE_EVT_WATCH_BASE 0x1600u
#define EDGE_EVT_ZMK_BASE 0x2100u

#define EDGE_EVT_UART0_RX (EDGE_EVT_BOARD_BASE + 0x01u)
#define EDGE_EVT_UART0_TX_DONE (EDGE_EVT_BOARD_BASE + 0x02u)
#define EDGE_EVT_BOARD_TIMER0 (EDGE_EVT_BOARD_BASE + 0x03u)
#define EDGE_EVT_DLT645_RX (EDGE_EVT_DLT645_BASE + 0x01u)
#define EDGE_EVT_DLMS_RX (EDGE_EVT_DLMS_BASE + 0x01u)
#define EDGE_EVT_RELAY_CHANGED (EDGE_EVT_RELAY_BASE + 0x01u)
#define EDGE_EVT_MODBUS_RX (EDGE_EVT_MODBUS_BASE + 0x01u)
#define EDGE_EVT_PULSE_COUNT (EDGE_EVT_PULSE_BASE + 0x01u)
#define EDGE_EVT_TAMPER_DETECTED (EDGE_EVT_PULSE_BASE + 0x02u)

#define EDGE_EVT_WATCH_TOUCH (EDGE_EVT_WATCH_BASE + 0x01u)
#define EDGE_EVT_WATCH_BUTTON (EDGE_EVT_WATCH_BASE + 0x02u)
#define EDGE_EVT_WATCH_WRIST_WAKE (EDGE_EVT_WATCH_BASE + 0x03u)
#define EDGE_EVT_WATCH_STEP_COUNT (EDGE_EVT_WATCH_BASE + 0x04u)
#define EDGE_EVT_WATCH_HEART_RATE (EDGE_EVT_WATCH_BASE + 0x05u)
#define EDGE_EVT_WATCH_BATTERY (EDGE_EVT_WATCH_BASE + 0x06u)
#define EDGE_EVT_WATCH_TIME_TICK (EDGE_EVT_WATCH_BASE + 0x07u)
#define EDGE_EVT_WATCH_NEW_HOUR (EDGE_EVT_WATCH_BASE + 0x08u)
#define EDGE_EVT_WATCH_NEW_DAY (EDGE_EVT_WATCH_BASE + 0x09u)
#define EDGE_EVT_WATCH_BLE_CONNECTED (EDGE_EVT_WATCH_BASE + 0x0Au)
#define EDGE_EVT_WATCH_BLE_DISCONNECTED (EDGE_EVT_WATCH_BASE + 0x0Bu)
#define EDGE_EVT_WATCH_ALARM_TRIGGER (EDGE_EVT_WATCH_BASE + 0x0Cu)
#define EDGE_EVT_WATCH_TIMER_EXPIRED (EDGE_EVT_WATCH_BASE + 0x0Du)
#define EDGE_EVT_WATCH_SETTINGS_CHANGED (EDGE_EVT_WATCH_BASE + 0x0Eu)
#define EDGE_EVT_WATCH_WEATHER_UPDATED (EDGE_EVT_WATCH_BASE + 0x0Fu)
#define EDGE_EVT_WATCH_MUSIC_UPDATED (EDGE_EVT_WATCH_BASE + 0x10u)
#define EDGE_EVT_WATCH_NAV_UPDATED (EDGE_EVT_WATCH_BASE + 0x11u)
#define EDGE_EVT_WATCH_NOTIF_NEW (EDGE_EVT_WATCH_BASE + 0x12u)
#define EDGE_EVT_WATCH_NOTIF_DISMISSED (EDGE_EVT_WATCH_BASE + 0x13u)
#define EDGE_EVT_WATCH_MOTION_STREAM (EDGE_EVT_WATCH_BASE + 0x14u)
#define EDGE_EVT_WATCH_FS_ACCESS (EDGE_EVT_WATCH_BASE + 0x15u)
#define EDGE_EVT_WATCH_DFU_STATE (EDGE_EVT_WATCH_BASE + 0x16u)

_Static_assert(EDGE_EVT_WATCH_TOUCH != EDGE_EVT_WATCH_BUTTON, "duplicate event ID");
_Static_assert(EDGE_EVT_WATCH_BLE_CONNECTED != EDGE_EVT_WATCH_BLE_DISCONNECTED,
               "duplicate event ID");
_Static_assert(EDGE_EVT_WATCH_ALARM_TRIGGER != EDGE_EVT_WATCH_TIMER_EXPIRED, "duplicate event ID");
_Static_assert(EDGE_EVT_WATCH_WEATHER_UPDATED != EDGE_EVT_WATCH_MUSIC_UPDATED,
               "duplicate event ID");
_Static_assert(EDGE_EVT_WATCH_NOTIF_NEW != EDGE_EVT_WATCH_NOTIF_DISMISSED, "duplicate event ID");
_Static_assert(EDGE_EVT_WATCH_FS_ACCESS != EDGE_EVT_WATCH_DFU_STATE, "duplicate event ID");

#define EDGE_EVT_ZMK_POSITION_STATE_CHANGED (EDGE_EVT_ZMK_BASE + 0x01u)
#define EDGE_EVT_ZMK_KEYCODE_STATE_CHANGED (EDGE_EVT_ZMK_BASE + 0x02u)
#define EDGE_EVT_ZMK_LAYER_STATE_CHANGED (EDGE_EVT_ZMK_BASE + 0x03u)
#define EDGE_EVT_ZMK_ACTIVITY_STATE_CHANGED (EDGE_EVT_ZMK_BASE + 0x04u)
#define EDGE_EVT_ZMK_ENDPOINT_CHANGED (EDGE_EVT_ZMK_BASE + 0x05u)
#define EDGE_EVT_ZMK_BATTERY_STATE_CHANGED (EDGE_EVT_ZMK_BASE + 0x06u)
#define EDGE_EVT_ZMK_WPM_STATE_CHANGED (EDGE_EVT_ZMK_BASE + 0x07u)
#define EDGE_EVT_ZMK_SPLIT_EVENT (EDGE_EVT_ZMK_BASE + 0x08u)
#define EDGE_EVT_ZMK_POINTING_MOTION (EDGE_EVT_ZMK_BASE + 0x09u)
#define EDGE_EVT_ZMK_POINTING_BUTTON (EDGE_EVT_ZMK_BASE + 0x0Au)
#define EDGE_EVT_ZMK_SENSOR_EVENT (EDGE_EVT_ZMK_BASE + 0x0Bu)
#define EDGE_EVT_ZMK_EXT_POWER_CHANGED (EDGE_EVT_ZMK_BASE + 0x0Cu)
#define EDGE_EVT_ZMK_STUDIO_EVENT (EDGE_EVT_ZMK_BASE + 0x0Du)

_Static_assert(EDGE_EVT_UART0_RX != EDGE_EVT_UART0_TX_DONE, "duplicate event ID");
_Static_assert(EDGE_EVT_UART0_RX != EDGE_EVT_BOARD_TIMER0, "duplicate event ID");
_Static_assert(EDGE_EVT_UART0_RX != EDGE_EVT_DLT645_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_UART0_RX != EDGE_EVT_DLMS_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_UART0_RX != EDGE_EVT_RELAY_CHANGED, "duplicate event ID");
_Static_assert(EDGE_EVT_UART0_TX_DONE != EDGE_EVT_BOARD_TIMER0, "duplicate event ID");
_Static_assert(EDGE_EVT_UART0_TX_DONE != EDGE_EVT_DLT645_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_UART0_TX_DONE != EDGE_EVT_DLMS_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_UART0_TX_DONE != EDGE_EVT_RELAY_CHANGED, "duplicate event ID");
_Static_assert(EDGE_EVT_BOARD_TIMER0 != EDGE_EVT_DLT645_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_BOARD_TIMER0 != EDGE_EVT_DLMS_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_BOARD_TIMER0 != EDGE_EVT_RELAY_CHANGED, "duplicate event ID");
_Static_assert(EDGE_EVT_DLT645_RX != EDGE_EVT_DLMS_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_DLT645_RX != EDGE_EVT_RELAY_CHANGED, "duplicate event ID");
_Static_assert(EDGE_EVT_DLMS_RX != EDGE_EVT_RELAY_CHANGED, "duplicate event ID");
_Static_assert(EDGE_EVT_UART0_RX != EDGE_EVT_MODBUS_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_UART0_TX_DONE != EDGE_EVT_MODBUS_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_BOARD_TIMER0 != EDGE_EVT_MODBUS_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_DLT645_RX != EDGE_EVT_MODBUS_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_DLMS_RX != EDGE_EVT_MODBUS_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_RELAY_CHANGED != EDGE_EVT_MODBUS_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_PULSE_COUNT != EDGE_EVT_TAMPER_DETECTED, "duplicate event ID");
_Static_assert(EDGE_EVT_PULSE_COUNT != EDGE_EVT_MODBUS_RX, "duplicate event ID");
_Static_assert(EDGE_EVT_PULSE_COUNT != EDGE_EVT_UART0_RX, "duplicate event ID");

#endif
