/*
 * GENERATED by tools/gen_mcconf_from_reference.py - do not edit by hand.
 * Source of truth: ../bldc/datatypes.h,
 *                  ../bldc/confgenerator.c,
 *                  ../bldc/motor/mcconf_default.h
 */

/*
 * One row per byte-stream item, in the reference's own order: array elements and
 * nested struct fields are rows of their own, exactly as the reference writes
 * them.
 *
 *   X(<wire kind>, <expression>, <scale>, <default>)
 *
 * Kinds: U8/U16/U32/I32 integers, F16 (2 bytes, value * scale), F32 (4 bytes,
 * fixed point, value * scale), F32A (4 bytes, IEEE float, subnormals zeroed),
 * NONE for a runtime value the reference does not serialise.
 *
 * The same list drives the writer, the reader and the defaults, so those three
 * cannot disagree, and APPCONF_WIRE_LEN is asserted to be the reference's
 * 290 bytes.
 */

#ifndef APPCONF_MANIFEST_H
#define APPCONF_MANIFEST_H

/* confgenerator.h: the signature this stream starts with. */
#define APPCONF_SIGNATURE 296593100u

#define APPCONF_WIRE(X)                                                                            \
    X(U8, controller_id, 0, HW_DEFAULT_ID)                                                         \
    X(U32, timeout_msec, 0, APPCONF_TIMEOUT_MSEC)                                                  \
    X(F32A, timeout_brake_current, 0, APPCONF_TIMEOUT_BRAKE_CURRENT)                               \
    X(U16, can_status_rate_1, 0, APPCONF_CAN_STATUS_RATE_1)                                        \
    X(U16, can_status_rate_2, 0, APPCONF_CAN_STATUS_RATE_2)                                        \
    X(U8, can_status_msgs_r1, 0, APPCONF_CAN_STATUS_MSGS_R1)                                       \
    X(U8, can_status_msgs_r2, 0, APPCONF_CAN_STATUS_MSGS_R2)                                       \
    X(U8, can_baud_rate, 0, APPCONF_CAN_BAUD_RATE)                                                 \
    X(U8, pairing_done, 0, APPCONF_PAIRING_DONE)                                                   \
    X(U8, permanent_uart_enabled, 0, APPCONF_PERMANENT_UART_ENABLED)                               \
    X(U8, shutdown_mode, 0, APPCONF_SHUTDOWN_MODE)                                                 \
    X(U8, can_mode, 0, APPCONF_CAN_MODE)                                                           \
    X(U8, uavcan_esc_index, 0, APPCONF_UAVCAN_ESC_INDEX)                                           \
    X(U8, uavcan_raw_mode, 0, APPCONF_UAVCAN_RAW_MODE)                                             \
    X(F32A, uavcan_raw_rpm_max, 0, APPCONF_UAVCAN_RAW_RPM_MAX)                                     \
    X(U8, uavcan_status_current_mode, 0, APPCONF_UAVCAN_STATUS_CURRENT_MODE)                       \
    X(U8, servo_out_enable, 0, APPCONF_SERVO_OUT_ENABLE)                                           \
    X(U8, kill_sw_mode, 0, APPCONF_KILL_SW_MODE)                                                   \
    X(U8, app_to_use, 0, APPCONF_APP_TO_USE)                                                       \
    X(U8, app_ppm_conf.ctrl_type, 0, APPCONF_PPM_CTRL_TYPE)                                        \
    X(F32A, app_ppm_conf.pid_max_erpm, 0, APPCONF_PPM_PID_MAX_ERPM)                                \
    X(F32A, app_ppm_conf.hyst, 0, APPCONF_PPM_HYST)                                                \
    X(F32A, app_ppm_conf.pulse_start, 0, APPCONF_PPM_PULSE_START)                                  \
    X(F32A, app_ppm_conf.pulse_end, 0, APPCONF_PPM_PULSE_END)                                      \
    X(F32A, app_ppm_conf.pulse_center, 0, APPCONF_PPM_PULSE_CENTER)                                \
    X(U8, app_ppm_conf.median_filter, 0, APPCONF_PPM_MEDIAN_FILTER)                                \
    X(U8, app_ppm_conf.safe_start, 0, APPCONF_PPM_SAFE_START)                                      \
    X(F32A, app_ppm_conf.throttle_exp, 0, APPCONF_PPM_THROTTLE_EXP)                                \
    X(F32A, app_ppm_conf.throttle_exp_brake, 0, APPCONF_PPM_THROTTLE_EXP_BRAKE)                    \
    X(U8, app_ppm_conf.throttle_exp_mode, 0, APPCONF_PPM_THROTTLE_EXP_MODE)                        \
    X(F32A, app_ppm_conf.ramp_time_pos, 0, APPCONF_PPM_RAMP_TIME_POS)                              \
    X(F32A, app_ppm_conf.ramp_time_neg, 0, APPCONF_PPM_RAMP_TIME_NEG)                              \
    X(U8, app_ppm_conf.multi_esc, 0, APPCONF_PPM_MULTI_ESC)                                        \
    X(U8, app_ppm_conf.tc, 0, APPCONF_PPM_TC)                                                      \
    X(F32A, app_ppm_conf.tc_max_diff, 0, APPCONF_PPM_TC_MAX_DIFF)                                  \
    X(F16, app_ppm_conf.max_erpm_for_dir, 1, APPCONF_PPM_MAX_ERPM_FOR_DIR)                         \
    X(F32A, app_ppm_conf.smart_rev_max_duty, 0, APPCONF_PPM_SMART_REV_MAX_DUTY)                    \
    X(F32A, app_ppm_conf.smart_rev_ramp_time, 0, APPCONF_PPM_SMART_REV_RAMP_TIME)                  \
    X(U8, app_adc_conf.ctrl_type, 0, APPCONF_ADC_CTRL_TYPE)                                        \
    X(F32A, app_adc_conf.hyst, 0, APPCONF_ADC_HYST)                                                \
    X(F16, app_adc_conf.voltage_start, 1000, APPCONF_ADC_VOLTAGE_START)                            \
    X(F16, app_adc_conf.voltage_end, 1000, APPCONF_ADC_VOLTAGE_END)                                \
    X(F16, app_adc_conf.voltage_min, 1000, APPCONF_ADC_VOLTAGE_MIN)                                \
    X(F16, app_adc_conf.voltage_max, 1000, APPCONF_ADC_VOLTAGE_MAX)                                \
    X(F16, app_adc_conf.voltage_center, 1000, APPCONF_ADC_VOLTAGE_CENTER)                          \
    X(F16, app_adc_conf.voltage2_start, 1000, APPCONF_ADC_VOLTAGE2_START)                          \
    X(F16, app_adc_conf.voltage2_end, 1000, APPCONF_ADC_VOLTAGE2_END)                              \
    X(U8, app_adc_conf.use_filter, 0, APPCONF_ADC_USE_FILTER)                                      \
    X(U8, app_adc_conf.safe_start, 0, APPCONF_ADC_SAFE_START)                                      \
    X(U8, app_adc_conf.buttons, 0, APPCONF_ADC_BUTTONS)                                            \
    X(U8, app_adc_conf.voltage_inverted, 0, APPCONF_ADC_VOLTAGE_INVERTED)                          \
    X(U8, app_adc_conf.voltage2_inverted, 0, APPCONF_ADC_VOLTAGE2_INVERTED)                        \
    X(F32A, app_adc_conf.throttle_exp, 0, APPCONF_ADC_THROTTLE_EXP)                                \
    X(F32A, app_adc_conf.throttle_exp_brake, 0, APPCONF_ADC_THROTTLE_EXP_BRAKE)                    \
    X(U8, app_adc_conf.throttle_exp_mode, 0, APPCONF_ADC_THROTTLE_EXP_MODE)                        \
    X(F32A, app_adc_conf.ramp_time_pos, 0, APPCONF_ADC_RAMP_TIME_POS)                              \
    X(F32A, app_adc_conf.ramp_time_neg, 0, APPCONF_ADC_RAMP_TIME_NEG)                              \
    X(U8, app_adc_conf.multi_esc, 0, APPCONF_ADC_MULTI_ESC)                                        \
    X(U8, app_adc_conf.tc, 0, APPCONF_ADC_TC)                                                      \
    X(F32A, app_adc_conf.tc_max_diff, 0, APPCONF_ADC_TC_MAX_DIFF)                                  \
    X(U16, app_adc_conf.update_rate_hz, 0, APPCONF_ADC_UPDATE_RATE_HZ)                             \
    X(F16, app_adc_conf.coast_brake_level, 1000, APPCONF_ADC_COAST_BRAKE_LEVEL)                    \
    X(F32A, app_adc_conf.coast_brake_ramp_time, 0, APPCONF_ADC_COAST_BRAKE_RAMP_TIME)              \
    X(U32, app_uart_baudrate, 0, APPCONF_UART_BAUDRATE)                                            \
    X(U8, app_chuk_conf.ctrl_type, 0, APPCONF_CHUK_CTRL_TYPE)                                      \
    X(F32A, app_chuk_conf.hyst, 0, APPCONF_CHUK_HYST)                                              \
    X(F32A, app_chuk_conf.ramp_time_pos, 0, APPCONF_CHUK_RAMP_TIME_POS)                            \
    X(F32A, app_chuk_conf.ramp_time_neg, 0, APPCONF_CHUK_RAMP_TIME_NEG)                            \
    X(F32A, app_chuk_conf.stick_erpm_per_s_in_cc, 0, APPCONF_STICK_ERPM_PER_S_IN_CC)               \
    X(F32A, app_chuk_conf.throttle_exp, 0, APPCONF_CHUK_THROTTLE_EXP)                              \
    X(F32A, app_chuk_conf.throttle_exp_brake, 0, APPCONF_CHUK_THROTTLE_EXP_BRAKE)                  \
    X(U8, app_chuk_conf.throttle_exp_mode, 0, APPCONF_CHUK_THROTTLE_EXP_MODE)                      \
    X(U8, app_chuk_conf.multi_esc, 0, APPCONF_CHUK_MULTI_ESC)                                      \
    X(U8, app_chuk_conf.tc, 0, APPCONF_CHUK_TC)                                                    \
    X(F32A, app_chuk_conf.tc_max_diff, 0, APPCONF_CHUK_TC_MAX_DIFF)                                \
    X(U8, app_chuk_conf.use_smart_rev, 0, APPCONF_CHUK_USE_SMART_REV)                              \
    X(F32A, app_chuk_conf.smart_rev_max_duty, 0, APPCONF_CHUK_SMART_REV_MAX_DUTY)                  \
    X(F32A, app_chuk_conf.smart_rev_ramp_time, 0, APPCONF_CHUK_SMART_REV_RAMP_TIME)                \
    X(F16, app_chuk_conf.coast_brake_level, 1000, APPCONF_CHUK_COAST_BRAKE_LEVEL)                  \
    X(F32A, app_chuk_conf.coast_brake_ramp_time, 0, APPCONF_CHUK_COAST_BRAKE_RAMP_TIME)            \
    X(U8, app_nrf_conf.speed, 0, APPCONF_NRF_SPEED)                                                \
    X(U8, app_nrf_conf.power, 0, APPCONF_NRF_POWER)                                                \
    X(U8, app_nrf_conf.crc_type, 0, APPCONF_NRF_CRC)                                               \
    X(U8, app_nrf_conf.retry_delay, 0, APPCONF_NRF_RETR_DELAY)                                     \
    X(U8, app_nrf_conf.retries, 0, APPCONF_NRF_RETRIES)                                            \
    X(U8, app_nrf_conf.channel, 0, APPCONF_NRF_CHANNEL)                                            \
    X(U8, app_nrf_conf.address[0], 0, APPCONF_NRF_ADDR_B0)                                         \
    X(U8, app_nrf_conf.address[1], 0, APPCONF_NRF_ADDR_B1)                                         \
    X(U8, app_nrf_conf.address[2], 0, APPCONF_NRF_ADDR_B2)                                         \
    X(U8, app_nrf_conf.send_crc_ack, 0, APPCONF_NRF_SEND_CRC_ACK)                                  \
    X(U8, app_pas_conf.ctrl_type, 0, APPCONF_PAS_CTRL_TYPE)                                        \
    X(U8, app_pas_conf.sensor_type, 0, APPCONF_PAS_SENSOR_TYPE)                                    \
    X(F16, app_pas_conf.current_scaling, 1000, APPCONF_PAS_CURRENT_SCALING)                        \
    X(F16, app_pas_conf.pedal_rpm_start, 10, APPCONF_PAS_PEDAL_RPM_START)                          \
    X(F16, app_pas_conf.pedal_rpm_end, 10, APPCONF_PAS_PEDAL_RPM_END)                              \
    X(U8, app_pas_conf.invert_pedal_direction, 0, APPCONF_PAS_INVERT_PEDAL_DIRECTION)              \
    X(U16, app_pas_conf.magnets, 0, APPCONF_PAS_MAGNETS)                                           \
    X(U8, app_pas_conf.use_filter, 0, APPCONF_PAS_USE_FILTER)                                      \
    X(F16, app_pas_conf.ramp_time_pos, 100, APPCONF_PAS_RAMP_TIME_POS)                             \
    X(F16, app_pas_conf.ramp_time_neg, 100, APPCONF_PAS_RAMP_TIME_NEG)                             \
    X(U16, app_pas_conf.update_rate_hz, 0, APPCONF_PAS_UPDATE_RATE_HZ)                             \
    X(U8, imu_conf.type, 0, APPCONF_IMU_TYPE)                                                      \
    X(U8, imu_conf.mode, 0, APPCONF_IMU_AHRS_MODE)                                                 \
    X(U8, imu_conf.filter, 0, APPCONF_IMU_FILTER)                                                  \
    X(F16, imu_conf.accel_lowpass_filter_x, 1, APPCONF_IMU_ACCEL_LOWPASS_FILTER_X)                 \
    X(F16, imu_conf.accel_lowpass_filter_y, 1, APPCONF_IMU_ACCEL_LOWPASS_FILTER_Y)                 \
    X(F16, imu_conf.accel_lowpass_filter_z, 1, APPCONF_IMU_ACCEL_LOWPASS_FILTER_Z)                 \
    X(F16, imu_conf.gyro_lowpass_filter, 1, APPCONF_IMU_GYRO_LOWPASS_FILTER)                       \
    X(U16, imu_conf.sample_rate_hz, 0, APPCONF_IMU_SAMPLE_RATE_HZ)                                 \
    X(U8, imu_conf.use_magnetometer, 0, APPCONF_IMU_USE_MAGNETOMETER)                              \
    X(F32A, imu_conf.accel_confidence_decay, 0, APPCONF_IMU_ACCEL_CONFIDENCE_DECAY)                \
    X(F32A, imu_conf.mahony_kp, 0, APPCONF_IMU_MAHONY_KP)                                          \
    X(F32A, imu_conf.mahony_ki, 0, APPCONF_IMU_MAHONY_KI)                                          \
    X(F32A, imu_conf.madgwick_beta, 0, APPCONF_IMU_MADGWICK_BETA)                                  \
    X(F32A, imu_conf.rot_roll, 0, APPCONF_IMU_ROT_ROLL)                                            \
    X(F32A, imu_conf.rot_pitch, 0, APPCONF_IMU_ROT_PITCH)                                          \
    X(F32A, imu_conf.rot_yaw, 0, APPCONF_IMU_ROT_YAW)                                              \
    X(F32A, imu_conf.accel_offsets[0], 0, APPCONF_IMU_A_OFFSET_0)                                  \
    X(F32A, imu_conf.accel_offsets[1], 0, APPCONF_IMU_A_OFFSET_1)                                  \
    X(F32A, imu_conf.accel_offsets[2], 0, APPCONF_IMU_A_OFFSET_2)                                  \
    X(F32A, imu_conf.gyro_offsets[0], 0, APPCONF_IMU_G_OFFSET_0)                                   \
    X(F32A, imu_conf.gyro_offsets[1], 0, APPCONF_IMU_G_OFFSET_1)                                   \
    X(F32A, imu_conf.gyro_offsets[2], 0, APPCONF_IMU_G_OFFSET_2)                                   \
    X(NONE, crc, 0, 0)
#define APPCONF_KIND_LEN_U8 1
#define APPCONF_KIND_LEN_U16 2
#define APPCONF_KIND_LEN_U32 4
#define APPCONF_KIND_LEN_I32 4
#define APPCONF_KIND_LEN_F16 2
#define APPCONF_KIND_LEN_F32 4
#define APPCONF_KIND_LEN_F32A 4
#define APPCONF_KIND_LEN_NONE 0
#define APPCONF_WIRE_LEN_ONE(kind, expr, scale, def) +APPCONF_KIND_LEN_##kind
#define APPCONF_WIRE_LEN (4 APPCONF_WIRE(APPCONF_WIRE_LEN_ONE))

#endif /* APPCONF_MANIFEST_H */
