/*
 * GENERATED by tools/gen_mcconf_from_reference.py - do not edit by hand.
 * Source of truth: ../bldc/datatypes.h,
 *                  ../bldc/confgenerator.c,
 *                  ../bldc/motor/mcconf_default.h
 */

#ifndef MCCONF_ENUMS_H
#define MCCONF_ENUMS_H

#include <stdbool.h>
#include <stdint.h>

typedef enum {
    BATTERY_TYPE_LIION_3_0__4_2,
    BATTERY_TYPE_LIIRON_2_6__3_6,
    BATTERY_TYPE_LEAD_ACID
} BATTERY_TYPE;

typedef enum {
    BMS_FWD_CAN_MODE_DISABLED = 0,
    BMS_FWD_CAN_MODE_USB_ONLY,
    BMS_FWD_CAN_MODE_ANY
} BMS_FWD_CAN_MODE;

typedef enum { BMS_TYPE_NONE = 0, BMS_TYPE_VESC } BMS_TYPE;

typedef enum {
    FOC_SPEED_SRC_CORRECTED = 0,
    FOC_SPEED_SRC_OBSERVER,
} FOC_SPEED_SRC;

typedef enum { MTPA_MODE_OFF = 0, MTPA_MODE_IQ_TARGET, MTPA_MODE_IQ_MEASURED } MTPA_MODE;

typedef enum {
    PID_RATE_25_HZ = 0,
    PID_RATE_50_HZ,
    PID_RATE_100_HZ,
    PID_RATE_250_HZ,
    PID_RATE_500_HZ,
    PID_RATE_1000_HZ,
    PID_RATE_2500_HZ,
    PID_RATE_5000_HZ,
    PID_RATE_10000_HZ,
} PID_RATE;

typedef enum {
    SAT_COMP_DISABLED = 0,
    SAT_COMP_FACTOR,
    SAT_COMP_LAMBDA,
    SAT_COMP_LAMBDA_AND_FACTOR
} SAT_COMP_MODE;

typedef enum {
    S_PID_SPEED_SRC_PLL = 0,
    S_PID_SPEED_SRC_FAST,
    S_PID_SPEED_SRC_FASTER,
} S_PID_SPEED_SRC;

typedef enum {
    DRV8301_OC_LIMIT = 0,
    DRV8301_OC_LATCH_SHUTDOWN,
    DRV8301_OC_REPORT_ONLY,
    DRV8301_OC_DISABLED
} drv8301_oc_mode;

typedef enum { HFI_SAMPLES_8 = 0, HFI_SAMPLES_16, HFI_SAMPLES_32 } foc_hfi_samples;

typedef enum { COMM_MODE_INTEGRATE = 0, COMM_MODE_DELAY } mc_comm_mode;

typedef enum {
    FOC_CC_DECOUPLING_DISABLED = 0,
    FOC_CC_DECOUPLING_CROSS,
    FOC_CC_DECOUPLING_BEMF,
    FOC_CC_DECOUPLING_CROSS_BEMF
} mc_foc_cc_decoupling_mode;

typedef enum {
    FOC_CONTROL_SAMPLE_MODE_V0 = 0,
    FOC_CONTROL_SAMPLE_MODE_V0_V7,
    FOC_CONTROL_SAMPLE_MODE_V0_V7_INTERPOL
} mc_foc_control_sample_mode;

typedef enum {
    FOC_CURRENT_SAMPLE_MODE_LONGEST_ZERO = 0,
    FOC_CURRENT_SAMPLE_MODE_ALL_SENSORS,
    FOC_CURRENT_SAMPLE_MODE_HIGH_CURRENT,
    FOC_CURRENT_SAMPLE_MODE_BEST_SENSOR // Experimental, not used!
} mc_foc_current_sample_mode;

typedef enum {
    FOC_AMB_MODE_SIX_VECTOR = 0,
    FOC_AMB_MODE_D_SINGLE_PULSE,
    FOC_AMB_MODE_D_DOUBLE_PULSE
} mc_foc_hfi_amb_mode;

typedef enum {
    FOC_SENSOR_MODE_SENSORLESS = 0,
    FOC_SENSOR_MODE_ENCODER,
    FOC_SENSOR_MODE_HALL,
    FOC_SENSOR_MODE_HFI,
    FOC_SENSOR_MODE_HFI_START,
    FOC_SENSOR_MODE_HFI_V2,
    FOC_SENSOR_MODE_HFI_V3,
    FOC_SENSOR_MODE_HFI_V4,
    FOC_SENSOR_MODE_HFI_V5,
    FOC_SENSOR_MODE_ENCODER_AB
} mc_foc_sensor_mode;

typedef enum { MOTOR_TYPE_BLDC = 0, MOTOR_TYPE_DC, MOTOR_TYPE_FOC } mc_motor_type;

typedef enum {
    PWM_MODE_NONSYNCHRONOUS_HISW = 0, // This mode is not recommended
    PWM_MODE_SYNCHRONOUS,             // The recommended and most tested mode
    PWM_MODE_BIPOLAR                  // Some glitches occasionally, can kill MOSFETs
} mc_pwm_mode;

typedef enum {
    SENSOR_MODE_SENSORLESS = 0,
    SENSOR_MODE_SENSORED,
    SENSOR_MODE_HYBRID
} mc_sensor_mode;

typedef enum {
    OUT_AUX_MODE_OFF = 0,
    OUT_AUX_MODE_ON_AFTER_2S,
    OUT_AUX_MODE_ON_AFTER_5S,
    OUT_AUX_MODE_ON_AFTER_10S,
    OUT_AUX_MODE_UNUSED,
    OUT_AUX_MODE_ON_WHEN_RUNNING,
    OUT_AUX_MODE_ON_WHEN_NOT_RUNNING,
    OUT_AUX_MODE_MOTOR_50,
    OUT_AUX_MODE_MOSFET_50,
    OUT_AUX_MODE_MOTOR_70,
    OUT_AUX_MODE_MOSFET_70,
    OUT_AUX_MODE_MOTOR_MOSFET_50,
    OUT_AUX_MODE_MOTOR_MOSFET_70,
} out_aux_mode;

typedef enum {
    SENSOR_PORT_MODE_HALL = 0,
    SENSOR_PORT_MODE_ABI,
    SENSOR_PORT_MODE_AS5047_SPI,
    SENSOR_PORT_MODE_AD2S1205,
    SENSOR_PORT_MODE_SINCOS,
    SENSOR_PORT_MODE_TS5700N8501,
    SENSOR_PORT_MODE_TS5700N8501_MULTITURN,
    SENSOR_PORT_MODE_MT6816_SPI_HW,
    SENSOR_PORT_MODE_AS5x47U_SPI,
    SENSOR_PORT_MODE_BISSC,
    SENSOR_PORT_MODE_TLE5012_SSC_SW,
    SENSOR_PORT_MODE_TLE5012_SSC_HW,
    SENSOR_PORT_MODE_CUSTOM_ENCODER,
    SENSOR_PORT_MODE_PWM,
    SENSOR_PORT_MODE_PWM_ABI,
    SENSOR_PORT_MODE_MA782,
    SENSOR_PORT_MODE_AMT22,
    SENSOR_PORT_MODE_MT6835_SPI_HW,
    SENSOR_PORT_MODE_PWM_ABI_INVERTED,
} sensor_port_mode;

typedef enum {
    TEMP_SENSOR_NTC_10K_25C = 0,
    TEMP_SENSOR_PTC_1K_100C,
    TEMP_SENSOR_KTY83_122,
    TEMP_SENSOR_NTC_100K_25C,
    TEMP_SENSOR_KTY84_130,
    TEMP_SENSOR_NTCX,
    TEMP_SENSOR_PTCX,
    TEMP_SENSOR_PT1000,
    TEMP_SENSOR_DISABLED
} temp_sensor_type;

typedef struct {
    BMS_TYPE type;
    uint8_t limit_mode;
    float t_limit_start;
    float t_limit_end;
    float soc_limit_start;
    float soc_limit_end;
    float vmin_limit_start;
    float vmin_limit_end;
    float vmax_limit_start;
    float vmax_limit_end;
    BMS_FWD_CAN_MODE fwd_can_mode;
} bms_config;

#endif /* MCCONF_ENUMS_H */
