/*
 * GENERATED by tools/gen_mcconf_from_reference.py - do not edit by hand.
 * Source of truth: ../bldc/datatypes.h,
 *                  ../bldc/confgenerator.c,
 *                  ../bldc/motor/mcconf_default.h
 */

/*
 * One row per byte-stream item, in the reference's own order, array elements
 * included (the reference writes hall_table[0]..[7] one at a time, and gives
 * each its own MCCONF_HALL_TAB_n default):
 *
 *   X(<wire kind>, <expression>, <scale>, <default>)
 *
 * Kinds: U8/U16/U32/I32 integers, F16 (2 bytes, value * scale), F32 (4 bytes,
 * fixed point, value * scale), F32A (4 bytes, IEEE float, subnormals zeroed),
 * BMS rows are the nested bms_config's own fields, written by the reference
 * one at a time; NONE marks a runtime value the reference does not serialise.
 *
 * The same list drives the writer, the reader and the defaults, so those three
 * cannot disagree; and MCCONF_WIRE_LEN is asserted to be the reference's 488.
 */

#ifndef MCCONF_MANIFEST_H
#define MCCONF_MANIFEST_H

/* confgenerator.h: the signature the stream starts with. */
#define MCCONF_SIGNATURE 3154770096u
#define APPCONF_SIGNATURE 296593100u

#define MCCONF_WIRE(X)                                                                             \
    X(U8, pwm_mode, 0, MCCONF_PWM_MODE)                                                            \
    X(U8, comm_mode, 0, MCCONF_COMM_MODE)                                                          \
    X(U8, motor_type, 0, MCCONF_DEFAULT_MOTOR_TYPE)                                                \
    X(U8, sensor_mode, 0, MCCONF_SENSOR_MODE)                                                      \
    X(F32A, l_current_max, 0, MCCONF_L_CURRENT_MAX)                                                \
    X(F32A, l_current_min, 0, MCCONF_L_CURRENT_MIN)                                                \
    X(F32A, l_in_current_max, 0, MCCONF_L_IN_CURRENT_MAX)                                          \
    X(F32A, l_in_current_min, 0, MCCONF_L_IN_CURRENT_MIN)                                          \
    X(F16, l_in_current_map_start, 10000, MCCONF_L_IN_CURRENT_MAP_START)                           \
    X(F16, l_in_current_map_filter, 10000, MCCONF_L_IN_CURRENT_MAP_FILTER)                         \
    X(F32A, l_abs_current_max, 0, MCCONF_L_MAX_ABS_CURRENT)                                        \
    X(F32A, l_min_erpm, 0, MCCONF_L_RPM_MIN)                                                       \
    X(F32A, l_max_erpm, 0, MCCONF_L_RPM_MAX)                                                       \
    X(F16, l_erpm_start, 10000, MCCONF_L_RPM_START)                                                \
    X(F32A, l_max_erpm_fbrake, 0, MCCONF_L_CURR_MAX_RPM_FBRAKE)                                    \
    X(F32A, l_max_erpm_fbrake_cc, 0, MCCONF_L_CURR_MAX_RPM_FBRAKE_CC)                              \
    X(F16, l_min_vin, 10, MCCONF_L_MIN_VOLTAGE)                                                    \
    X(F16, l_max_vin, 10, MCCONF_L_MAX_VOLTAGE)                                                    \
    X(F16, l_battery_cut_start, 10, MCCONF_L_BATTERY_CUT_START)                                    \
    X(F16, l_battery_cut_end, 10, MCCONF_L_BATTERY_CUT_END)                                        \
    X(F16, l_battery_regen_cut_start, 10, MCCONF_L_BATTERY_REGEN_CUT_START)                        \
    X(F16, l_battery_regen_cut_end, 10, MCCONF_L_BATTERY_REGEN_CUT_END)                            \
    X(U8, l_slow_abs_current, 0, MCCONF_L_SLOW_ABS_OVERCURRENT)                                    \
    X(U8, l_temp_fet_start, 0, MCCONF_L_LIM_TEMP_FET_START)                                        \
    X(U8, l_temp_fet_end, 0, MCCONF_L_LIM_TEMP_FET_END)                                            \
    X(U8, l_temp_motor_start, 0, MCCONF_L_LIM_TEMP_MOTOR_START)                                    \
    X(U8, l_temp_motor_end, 0, MCCONF_L_LIM_TEMP_MOTOR_END)                                        \
    X(F16, l_temp_accel_dec, 10000, MCCONF_L_LIM_TEMP_ACCEL_DEC)                                   \
    X(F16, l_min_duty, 10000, MCCONF_L_MIN_DUTY)                                                   \
    X(F16, l_max_duty, 10000, MCCONF_L_MAX_DUTY)                                                   \
    X(F32A, l_watt_max, 0, MCCONF_L_WATT_MAX)                                                      \
    X(F32A, l_watt_min, 0, MCCONF_L_WATT_MIN)                                                      \
    X(F16, l_current_max_scale, 10000, MCCONF_L_CURRENT_MAX_SCALE)                                 \
    X(F16, l_current_min_scale, 10000, MCCONF_L_CURRENT_MIN_SCALE)                                 \
    X(F16, l_duty_start, 10000, MCCONF_L_DUTY_START)                                               \
    X(U8, l_additional_faults, 0, MCCONF_L_ADDITIONAL_FAULTS)                                      \
    X(F32A, sl_min_erpm, 0, MCCONF_SL_MIN_RPM)                                                     \
    X(F32A, sl_min_erpm_cycle_int_limit, 0, MCCONF_SL_MIN_ERPM_CYCLE_INT_LIMIT)                    \
    X(F32A, sl_max_fullbreak_current_dir_change, 0, MCCONF_SL_MAX_FB_CURR_DIR_CHANGE)              \
    X(F16, sl_cycle_int_limit, 10, MCCONF_SL_CYCLE_INT_LIMIT)                                      \
    X(F16, sl_phase_advance_at_br, 10000, MCCONF_SL_PHASE_ADVANCE_AT_BR)                           \
    X(F32A, sl_cycle_int_rpm_br, 0, MCCONF_SL_CYCLE_INT_BR)                                        \
    X(F32A, sl_bemf_coupling_k, 0, MCCONF_SL_BEMF_COUPLING_K)                                      \
    X(U8, hall_table[0], 0, MCCONF_HALL_TAB_0)                                                     \
    X(U8, hall_table[1], 0, MCCONF_HALL_TAB_1)                                                     \
    X(U8, hall_table[2], 0, MCCONF_HALL_TAB_2)                                                     \
    X(U8, hall_table[3], 0, MCCONF_HALL_TAB_3)                                                     \
    X(U8, hall_table[4], 0, MCCONF_HALL_TAB_4)                                                     \
    X(U8, hall_table[5], 0, MCCONF_HALL_TAB_5)                                                     \
    X(U8, hall_table[6], 0, MCCONF_HALL_TAB_6)                                                     \
    X(U8, hall_table[7], 0, MCCONF_HALL_TAB_7)                                                     \
    X(F32A, hall_sl_erpm, 0, MCCONF_HALL_ERPM)                                                     \
    X(F32A, foc_current_kp, 0, MCCONF_FOC_CURRENT_KP)                                              \
    X(F32A, foc_current_ki, 0, MCCONF_FOC_CURRENT_KI)                                              \
    X(F32A, foc_f_zv, 0, MCCONF_FOC_F_ZV)                                                          \
    X(F32A, foc_dt_us, 0, MCCONF_FOC_DT_US)                                                        \
    X(U8, foc_encoder_inverted, 0, MCCONF_FOC_ENCODER_INVERTED)                                    \
    X(F32A, foc_encoder_offset, 0, MCCONF_FOC_ENCODER_OFFSET)                                      \
    X(F32A, foc_encoder_ratio, 0, MCCONF_FOC_ENCODER_RATIO)                                        \
    X(U8, foc_sensor_mode, 0, MCCONF_FOC_SENSOR_MODE)                                              \
    X(F32A, foc_pll_kp, 0, MCCONF_FOC_PLL_KP)                                                      \
    X(F32A, foc_pll_ki, 0, MCCONF_FOC_PLL_KI)                                                      \
    X(F32A, foc_motor_l, 0, MCCONF_FOC_MOTOR_L)                                                    \
    X(F32A, foc_motor_ld_lq_diff, 0, MCCONF_FOC_MOTOR_LD_LQ_DIFF)                                  \
    X(F32A, foc_motor_r, 0, MCCONF_FOC_MOTOR_R)                                                    \
    X(F32A, foc_motor_flux_linkage, 0, MCCONF_FOC_MOTOR_FLUX_LINKAGE)                              \
    X(F32A, foc_observer_gain, 0, MCCONF_FOC_OBSERVER_GAIN)                                        \
    X(F32A, foc_observer_gain_slow, 0, MCCONF_FOC_OBSERVER_GAIN_SLOW)                              \
    X(F16, foc_observer_offset, 1000, MCCONF_FOC_OBSERVER_OFFSET)                                  \
    X(F32A, foc_duty_dowmramp_kp, 0, MCCONF_FOC_DUTY_DOWNRAMP_KP)                                  \
    X(F32A, foc_duty_dowmramp_ki, 0, MCCONF_FOC_DUTY_DOWNRAMP_KI)                                  \
    X(F16, foc_start_curr_dec, 10000, MCCONF_FOC_START_CURR_DEC)                                   \
    X(F32A, foc_start_curr_dec_rpm, 0, MCCONF_FOC_START_CURR_DEC_RPM)                              \
    X(F32A, foc_openloop_rpm, 0, MCCONF_FOC_OPENLOOP_RPM)                                          \
    X(F16, foc_openloop_rpm_low, 1000, MCCONF_FOC_OPENLOOP_RPM_LOW)                                \
    X(F16, foc_sl_openloop_hyst, 100, MCCONF_FOC_SL_OPENLOOP_HYST)                                 \
    X(F16, foc_sl_openloop_time_lock, 100, MCCONF_FOC_SL_OPENLOOP_T_LOCK)                          \
    X(F16, foc_sl_openloop_time_ramp, 100, MCCONF_FOC_SL_OPENLOOP_T_RAMP)                          \
    X(F16, foc_sl_openloop_time, 100, MCCONF_FOC_SL_OPENLOOP_TIME)                                 \
    X(F16, foc_sl_openloop_boost_q, 100, MCCONF_FOC_SL_OPENLOOP_BOOST_Q)                           \
    X(F16, foc_sl_openloop_max_q, 100, MCCONF_FOC_SL_OPENLOOP_MAX_Q)                               \
    X(U8, foc_hall_table[0], 0, MCCONF_FOC_HALL_TAB_0)                                             \
    X(U8, foc_hall_table[1], 0, MCCONF_FOC_HALL_TAB_1)                                             \
    X(U8, foc_hall_table[2], 0, MCCONF_FOC_HALL_TAB_2)                                             \
    X(U8, foc_hall_table[3], 0, MCCONF_FOC_HALL_TAB_3)                                             \
    X(U8, foc_hall_table[4], 0, MCCONF_FOC_HALL_TAB_4)                                             \
    X(U8, foc_hall_table[5], 0, MCCONF_FOC_HALL_TAB_5)                                             \
    X(U8, foc_hall_table[6], 0, MCCONF_FOC_HALL_TAB_6)                                             \
    X(U8, foc_hall_table[7], 0, MCCONF_FOC_HALL_TAB_7)                                             \
    X(F32A, foc_hall_interp_erpm, 0, MCCONF_FOC_HALL_INTERP_ERPM)                                  \
    X(F32A, foc_sl_erpm_start, 0, MCCONF_FOC_SL_ERPM_START)                                        \
    X(F32A, foc_sl_erpm, 0, MCCONF_FOC_SL_ERPM)                                                    \
    X(U8, foc_control_sample_mode, 0, MCCONF_FOC_CONTROL_SAMPLE_MODE)                              \
    X(U8, foc_current_sample_mode, 0, MCCONF_FOC_CURRENT_SAMPLE_MODE)                              \
    X(U8, foc_sat_comp_mode, 0, MCCONF_FOC_SAT_COMP_MODE)                                          \
    X(F16, foc_sat_comp, 1000, MCCONF_FOC_SAT_COMP)                                                \
    X(U8, foc_temp_comp, 0, MCCONF_FOC_TEMP_COMP)                                                  \
    X(F16, foc_temp_comp_base_temp, 100, MCCONF_FOC_TEMP_COMP_BASE_TEMP)                           \
    X(F16, foc_current_filter_const, 10000, MCCONF_FOC_CURRENT_FILTER_CONST)                       \
    X(U8, foc_cc_decoupling, 0, MCCONF_FOC_CC_DECOUPLING)                                          \
    X(U8, foc_observer_type, 0, MCCONF_FOC_OBSERVER_TYPE)                                          \
    X(U8, foc_hfi_amb_mode, 0, MCCONF_FOC_HFI_AMB_MODE)                                            \
    X(F16, foc_hfi_amb_current, 10, MCCONF_FOC_HFI_AMB_CURRENT)                                    \
    X(U8, foc_hfi_amb_tres, 0, MCCONF_FOC_HFI_AMB_TRES)                                            \
    X(F16, foc_hfi_voltage_start, 10, MCCONF_FOC_HFI_VOLTAGE_START)                                \
    X(F16, foc_hfi_voltage_run, 10, MCCONF_FOC_HFI_VOLTAGE_RUN)                                    \
    X(F16, foc_hfi_voltage_max, 10, MCCONF_FOC_HFI_VOLTAGE_MAX)                                    \
    X(F16, foc_hfi_gain, 1000, MCCONF_FOC_HFI_GAIN)                                                \
    X(F16, foc_hfi_max_err, 1000, MCCONF_FOC_HFI_MAX_ERR)                                          \
    X(F16, foc_hfi_hyst, 100, MCCONF_FOC_HFI_HYST)                                                 \
    X(F32A, foc_sl_erpm_hfi, 0, MCCONF_FOC_SL_ERPM_HFI)                                            \
    X(F32A, foc_hfi_reset_erpm, 0, MCCONF_FOC_HFI_RESET_ERPM)                                      \
    X(U16, foc_hfi_start_samples, 0, MCCONF_FOC_HFI_START_SAMPLES)                                 \
    X(F32A, foc_hfi_obs_ovr_sec, 0, MCCONF_FOC_HFI_OBS_OVR_SEC)                                    \
    X(U8, foc_hfi_samples, 0, MCCONF_FOC_HFI_SAMPLES)                                              \
    X(U8, foc_offsets_cal_mode, 0, MCCONF_FOC_OFFSETS_CAL_MODE)                                    \
    X(F32A, foc_offsets_current[0], 0, MCCONF_FOC_OFFSETS_CURRENT_0)                               \
    X(F32A, foc_offsets_current[1], 0, MCCONF_FOC_OFFSETS_CURRENT_1)                               \
    X(F32A, foc_offsets_current[2], 0, MCCONF_FOC_OFFSETS_CURRENT_2)                               \
    X(F16, foc_offsets_voltage[0], 10000, MCCONF_FOC_OFFSETS_VOLTAGE_0)                            \
    X(F16, foc_offsets_voltage[1], 10000, MCCONF_FOC_OFFSETS_VOLTAGE_1)                            \
    X(F16, foc_offsets_voltage[2], 10000, MCCONF_FOC_OFFSETS_VOLTAGE_2)                            \
    X(F16, foc_offsets_voltage_undriven[0], 10000, MCCONF_FOC_OFFSETS_VOLTAGE_UNDRIVEN_0)          \
    X(F16, foc_offsets_voltage_undriven[1], 10000, MCCONF_FOC_OFFSETS_VOLTAGE_UNDRIVEN_1)          \
    X(F16, foc_offsets_voltage_undriven[2], 10000, MCCONF_FOC_OFFSETS_VOLTAGE_UNDRIVEN_2)          \
    X(U8, foc_phase_filter_enable, 0, MCCONF_FOC_PHASE_FILTER_ENABLE)                              \
    X(U8, foc_phase_filter_disable_fault, 0, MCCONF_FOC_PHASE_FILTER_DISABLE_FAULT)                \
    X(F32A, foc_phase_filter_max_erpm, 0, MCCONF_FOC_PHASE_FILTER_MAX_ERPM)                        \
    X(U8, foc_mtpa_mode, 0, MCCONF_FOC_MTPA_MODE)                                                  \
    X(F32A, foc_fw_current_max, 0, MCCONF_FOC_FW_CURRENT_MAX)                                      \
    X(F16, foc_fw_duty_start, 10000, MCCONF_FOC_FW_DUTY_START)                                     \
    X(F16, foc_fw_ramp_time, 1000, MCCONF_FOC_FW_RAMP_TIME)                                        \
    X(F16, foc_fw_q_current_factor, 10000, MCCONF_FOC_FW_Q_CURRENT_FACTOR)                         \
    X(F16, foc_fw_backoff, 1000, MCCONF_FOC_FW_BACKOFF)                                            \
    X(U8, foc_speed_soure, 0, MCCONF_FOC_SPEED_SOURCE)                                             \
    X(U8, foc_short_ls_on_zero_duty, 0, MCCONF_FOC_SHORT_LS_ON_ZERO_DUTY)                          \
    X(F16, foc_overmod_factor, 10000, MCCONF_FOC_OVERMOD_FACTOR)                                   \
    X(F16, foc_mag_vd_max, 10000, MCCONF_FOC_MAG_VD_MAX)                                           \
    X(U8, sp_pid_loop_rate, 0, MCCONF_SP_PID_LOOP_RATE)                                            \
    X(F32A, s_pid_kp, 0, MCCONF_S_PID_KP)                                                          \
    X(F32A, s_pid_ki, 0, MCCONF_S_PID_KI)                                                          \
    X(F32A, s_pid_kd, 0, MCCONF_S_PID_KD)                                                          \
    X(F16, s_pid_kd_filter, 10000, MCCONF_S_PID_KD_FILTER)                                         \
    X(F32A, s_pid_min_erpm, 0, MCCONF_S_PID_MIN_RPM)                                               \
    X(U8, s_pid_allow_braking, 0, MCCONF_S_PID_ALLOW_BRAKING)                                      \
    X(F32A, s_pid_ramp_erpms_s, 0, MCCONF_S_PID_RAMP_ERPMS_S)                                      \
    X(U8, s_pid_speed_source, 0, MCCONF_S_PID_SPEED_SOURCE)                                        \
    X(F32A, p_pid_kp, 0, MCCONF_P_PID_KP)                                                          \
    X(F32A, p_pid_ki, 0, MCCONF_P_PID_KI)                                                          \
    X(F32A, p_pid_kd, 0, MCCONF_P_PID_KD)                                                          \
    X(F32A, p_pid_kd_proc, 0, MCCONF_P_PID_KD_PROC)                                                \
    X(F16, p_pid_kd_filter, 10000, MCCONF_P_PID_KD_FILTER)                                         \
    X(F32A, p_pid_ang_div, 0, MCCONF_P_PID_ANG_DIV)                                                \
    X(F16, p_pid_gain_dec_angle, 10, MCCONF_P_PID_GAIN_DEC_ANGLE)                                  \
    X(F32A, p_pid_offset, 0, MCCONF_P_PID_OFFSET)                                                  \
    X(F16, cc_startup_boost_duty, 10000, MCCONF_CC_STARTUP_BOOST_DUTY)                             \
    X(F32A, cc_min_current, 0, MCCONF_CC_MIN_CURRENT)                                              \
    X(F32A, cc_gain, 0, MCCONF_CC_GAIN)                                                            \
    X(F16, cc_ramp_step_max, 10000, MCCONF_CC_RAMP_STEP)                                           \
    X(I32, m_fault_stop_time_ms, 0, MCCONF_M_FAULT_STOP_TIME)                                      \
    X(F16, m_duty_ramp_step, 10000, MCCONF_M_RAMP_STEP)                                            \
    X(F32A, m_current_backoff_gain, 0, MCCONF_M_CURRENT_BACKOFF_GAIN)                              \
    X(U32, m_encoder_counts, 0, MCCONF_M_ENCODER_COUNTS)                                           \
    X(F16, m_encoder_sin_amp, 1000, MCCONF_M_ENCODER_SIN_AMP)                                      \
    X(F16, m_encoder_cos_amp, 1000, MCCONF_M_ENCODER_COS_AMP)                                      \
    X(F16, m_encoder_sin_offset, 1000, MCCONF_M_ENCODER_SIN_OFFSET)                                \
    X(F16, m_encoder_cos_offset, 1000, MCCONF_M_ENCODER_COS_OFFSET)                                \
    X(F16, m_encoder_sincos_filter_constant, 1000, MCCONF_M_ENCODER_SINCOS_FILTER)                 \
    X(F16, m_encoder_sincos_phase_correction, 1000, MCCONF_M_ENCODER_SINCOS_PHASE)                 \
    X(U8, m_sensor_port_mode, 0, MCCONF_M_SENSOR_PORT_MODE)                                        \
    X(U8, m_invert_direction, 0, MCCONF_M_INVERT_DIRECTION)                                        \
    X(U8, m_drv8301_oc_mode, 0, MCCONF_M_DRV8301_OC_MODE)                                          \
    X(U8, m_drv8301_oc_adj, 0, MCCONF_M_DRV8301_OC_ADJ)                                            \
    X(F32A, m_bldc_f_sw_min, 0, MCCONF_M_BLDC_F_SW_MIN)                                            \
    X(F32A, m_bldc_f_sw_max, 0, MCCONF_M_BLDC_F_SW_MAX)                                            \
    X(F32A, m_dc_f_sw, 0, MCCONF_M_DC_F_SW)                                                        \
    X(F32A, m_ntc_motor_beta, 0, MCCONF_M_NTC_MOTOR_BETA)                                          \
    X(U8, m_out_aux_mode, 0, MCCONF_M_OUT_AUX_MODE)                                                \
    X(U8, m_motor_temp_sens_type, 0, MCCONF_M_MOTOR_TEMP_SENS_TYPE)                                \
    X(F32A, m_ptc_motor_coeff, 0, MCCONF_M_PTC_MOTOR_COEFF)                                        \
    X(F16, m_ntcx_ptcx_res, 0.1, MCCONF_M_NTCX_PTCX_RES)                                           \
    X(F16, m_ntcx_ptcx_temp_base, 10, MCCONF_M_NTCX_PTCX_BASE_TEMP)                                \
    X(U8, m_hall_extra_samples, 0, MCCONF_M_HALL_EXTRA_SAMPLES)                                    \
    X(U8, m_batt_filter_const, 0, MCCONF_M_BATT_FILTER_CONST)                                      \
    X(U8, si_motor_poles, 0, MCCONF_SI_MOTOR_POLES)                                                \
    X(F32A, si_gear_ratio, 0, MCCONF_SI_GEAR_RATIO)                                                \
    X(F32A, si_wheel_diameter, 0, MCCONF_SI_WHEEL_DIAMETER)                                        \
    X(U8, si_battery_type, 0, MCCONF_SI_BATTERY_TYPE)                                              \
    X(U8, si_battery_cells, 0, MCCONF_SI_BATTERY_CELLS)                                            \
    X(F32A, si_battery_ah, 0, MCCONF_SI_BATTERY_AH)                                                \
    X(F32A, si_motor_nl_current, 0, MCCONF_SI_MOTOR_NL_CURRENT)                                    \
    X(U8, bms.type, 0, MCCONF_BMS_TYPE)                                                            \
    X(U8, bms.limit_mode, 0, MCCONF_BMS_LIMIT_MODE)                                                \
    X(U8, bms.t_limit_start, 0, MCCONF_BMS_T_LIMIT_START)                                          \
    X(U8, bms.t_limit_end, 0, MCCONF_BMS_T_LIMIT_END)                                              \
    X(F16, bms.soc_limit_start, 1000, MCCONF_BMS_SOC_LIMIT_START)                                  \
    X(F16, bms.soc_limit_end, 1000, MCCONF_BMS_SOC_LIMIT_END)                                      \
    X(F16, bms.vmin_limit_start, 1000, MCCONF_BMS_VMIN_LIMIT_START)                                \
    X(F16, bms.vmin_limit_end, 1000, MCCONF_BMS_VMIN_LIMIT_END)                                    \
    X(F16, bms.vmax_limit_start, 1000, MCCONF_BMS_VMAX_LIMIT_START)                                \
    X(F16, bms.vmax_limit_end, 1000, MCCONF_BMS_VMAX_LIMIT_END)                                    \
    X(U8, bms.fwd_can_mode, 0, MCCONF_BMS_FWD_CAN_MODE)                                            \
    X(NONE, lo_current_max, 0, 0)                                                                  \
    X(NONE, lo_current_min, 0, 0)                                                                  \
    X(NONE, lo_in_current_max, 0, 0)                                                               \
    X(NONE, lo_in_current_min, 0, 0)                                                               \
    X(NONE, crc, 0, 0)

#define MCCONF_KIND_LEN_U8 1
#define MCCONF_KIND_LEN_U16 2
#define MCCONF_KIND_LEN_U32 4
#define MCCONF_KIND_LEN_I32 4
#define MCCONF_KIND_LEN_F16 2
#define MCCONF_KIND_LEN_F32 4
#define MCCONF_KIND_LEN_F32A 4
#define MCCONF_KIND_LEN_NONE 0
#define MCCONF_WIRE_LEN_ONE(kind, expr, scale, def) +MCCONF_KIND_LEN_##kind
#define MCCONF_WIRE_LEN (4 MCCONF_WIRE(MCCONF_WIRE_LEN_ONE))

#endif /* MCCONF_MANIFEST_H */
