/*
 * GENERATED by tools/gen_mcconf_from_reference.py - do not edit by hand.
 * Source of truth: ../bldc/datatypes.h,
 *                  ../bldc/confgenerator.c,
 *                  ../bldc/motor/mcconf_default.h
 */

#ifndef VESC_STRUCTS_H
#define VESC_STRUCTS_H

#include "motor_config/vesc_enums.h"

typedef struct {
    adc_control_type ctrl_type;
    float hyst;
    float voltage_start;
    float voltage_end;
    float voltage_min;
    float voltage_max;
    float voltage_center;
    float voltage2_start;
    float voltage2_end;
    bool use_filter;
    SAFE_START_MODE safe_start;
    uint8_t buttons;
    bool voltage_inverted;
    bool voltage2_inverted;
    float throttle_exp;
    float throttle_exp_brake;
    thr_exp_mode throttle_exp_mode;
    float ramp_time_pos;
    float ramp_time_neg;
    bool multi_esc;
    bool tc;
    float tc_max_diff;
    uint32_t update_rate_hz;
    float coast_brake_level;
    float coast_brake_ramp_time;
} adc_config;

typedef struct {
    BMS_TYPE type;
    uint8_t limit_mode;
    float t_limit_start;
    float t_limit_end;
    float soc_limit_start;
    float soc_limit_end;
    float vmin_limit_start;
    float vmin_limit_end;
    float vmax_limit_start;
    float vmax_limit_end;
    BMS_FWD_CAN_MODE fwd_can_mode;
} bms_config;

typedef struct {
    chuk_control_type ctrl_type;
    float hyst;
    float ramp_time_pos;
    float ramp_time_neg;
    float stick_erpm_per_s_in_cc;
    float throttle_exp;
    float throttle_exp_brake;
    thr_exp_mode throttle_exp_mode;
    bool multi_esc;
    bool tc;
    float tc_max_diff;
    bool use_smart_rev;
    float smart_rev_max_duty;
    float smart_rev_ramp_time;
    float coast_brake_level;
    float coast_brake_ramp_time;
} chuk_config;

typedef struct {
    IMU_TYPE type;
    AHRS_MODE mode;
    IMU_FILTER filter;
    float accel_lowpass_filter_x;
    float accel_lowpass_filter_y;
    float accel_lowpass_filter_z;
    float gyro_lowpass_filter;
    int sample_rate_hz;
    bool use_magnetometer;
    float accel_confidence_decay;
    float mahony_kp;
    float mahony_ki;
    float madgwick_beta;
    float rot_roll;
    float rot_pitch;
    float rot_yaw;
    float accel_offsets[3];
    float gyro_offsets[3];
} imu_config;

typedef struct {
    NRF_SPEED speed;
    NRF_POWER power;
    NRF_CRC crc_type;
    NRF_RETR_DELAY retry_delay;
    unsigned char retries;
    unsigned char channel;
    unsigned char address[3];
    bool send_crc_ack;
} nrf_config;

typedef struct {
    pas_control_type ctrl_type;
    pas_sensor_type sensor_type;
    float current_scaling;
    float pedal_rpm_start;
    float pedal_rpm_end;
    bool invert_pedal_direction;
    uint8_t magnets;
    bool use_filter;
    float ramp_time_pos;
    float ramp_time_neg;
    uint32_t update_rate_hz;
} pas_config;

typedef struct {
    ppm_control_type ctrl_type;
    float pid_max_erpm;
    float hyst;
    float pulse_start;
    float pulse_end;
    float pulse_center;
    bool median_filter;
    SAFE_START_MODE safe_start;
    float throttle_exp;
    float throttle_exp_brake;
    thr_exp_mode throttle_exp_mode;
    float ramp_time_pos;
    float ramp_time_neg;
    bool multi_esc;
    bool tc;
    float tc_max_diff;
    float max_erpm_for_dir;
    float smart_rev_max_duty;
    float smart_rev_ramp_time;
} ppm_config;

#endif /* VESC_STRUCTS_H */
