/*
 * HFI's excitation tables, generated by tools/gen_hfi_from_reference.py from the reference's
 * util/utils_math.c. Do not edit: change the generator or the reference.
 *
 * They are rounded six-decimal cosines and sines, not what cosf/sinf produce, so they are
 * extracted rather than recomputed - HFI's angle error is computed from these numbers every
 * cycle, and a last-digit difference there would accumulate.
 *
 * They live in the app because an app may not depend on infra (D30), the same reason vesc_can and
 * motor_config each carry their own crc16.
 */
#ifndef APP_FOC_CORE_HFI_TABLES_H
#define APP_FOC_CORE_HFI_TABLES_H

/* vendor/bldc/util/utils_math.c: const float utils_tab_cos_32_1[] */
const float foc_utils_tab_cos_32_1[] = {
    1.000000,  0.980785,  0.923880,  0.831470,  0.707107,  0.555570,  0.382683,  0.195090,
    0.000000,  -0.195090, -0.382683, -0.555570, -0.707107, -0.831470, -0.923880, -0.980785,
    -1.000000, -0.980785, -0.923880, -0.831470, -0.707107, -0.555570, -0.382683, -0.195090,
    -0.000000, 0.195090,  0.382683,  0.555570,  0.707107,  0.831470,  0.923880,  0.980785,
};

/* vendor/bldc/util/utils_math.c: const float utils_tab_sin_32_1[] */
const float foc_utils_tab_sin_32_1[] = {
    0.000000,  0.195090,  0.382683,  0.555570,  0.707107,  0.831470,  0.923880,  0.980785,
    1.000000,  0.980785,  0.923880,  0.831470,  0.707107,  0.555570,  0.382683,  0.195090,
    0.000000,  -0.195090, -0.382683, -0.555570, -0.707107, -0.831470, -0.923880, -0.980785,
    -1.000000, -0.980785, -0.923880, -0.831470, -0.707107, -0.555570, -0.382683, -0.195090,
};

/* vendor/bldc/util/utils_math.c: const float utils_tab_cos_32_2[] */
const float foc_utils_tab_cos_32_2[] = {
    1.000000,  0.923880,  0.707107,  0.382683,  0.000000,  -0.382683, -0.707107, -0.923880,
    -1.000000, -0.923880, -0.707107, -0.382683, -0.000000, 0.382683,  0.707107,  0.923880,
    1.000000,  0.923880,  0.707107,  0.382683,  0.000000,  -0.382683, -0.707107, -0.923880,
    -1.000000, -0.923880, -0.707107, -0.382683, -0.000000, 0.382683,  0.707107,  0.923880,
};

/* vendor/bldc/util/utils_math.c: const float utils_tab_sin_32_2[] */
const float foc_utils_tab_sin_32_2[] = {
    0.000000,  0.382683,  0.707107,  0.923880,  1.000000,  0.923880,  0.707107,  0.382683,
    0.000000,  -0.382683, -0.707107, -0.923880, -1.000000, -0.923880, -0.707107, -0.382683,
    -0.000000, 0.382683,  0.707107,  0.923880,  1.000000,  0.923880,  0.707107,  0.382683,
    0.000000,  -0.382683, -0.707107, -0.923880, -1.000000, -0.923880, -0.707107, -0.382683,
};

#endif /* APP_FOC_CORE_HFI_TABLES_H */
