#!/usr/bin/env python3
"""Generate the mc_configuration layout, wire manifest and defaults from the reference.

The reference's own confgenerator.c is autogenerated by VESC Tool, so the port does the
same thing the reference does: one checked-in generator, re-runnable when the reference
moves, instead of a hand-transcribed table that silently rots.

Inputs (the reference tree, `vendor/bldc`):
  datatypes.h              - the enum bodies, bms_config and mc_configuration members
  confgenerator.c          - confgenerator_serialize_mcconf() gives the wire order, kind
                             and scale per field; confgenerator_set_defaults_mcconf()
                             gives every default
  motor/mcconf_default.h   - the MCCONF_* macros the defaults are written in terms of

Outputs (three headers, each stamped "generated"):
  app/motor_config/include/motor_config/mcconf_enums.h     enum bodies + bms_config
  app/motor_config/include/motor_config/mcconf_manifest.h   MCCONF_FIELDS(X) + lengths
  app/motor_config/src/mcconf_defaults.h                    MCCONF_* values, with lines

The manifest is the single source for the struct, the defaults and (once the codec is
rewritten) the byte stream. One row per mc_configuration member:

  X(<c type>, <name>, <array size>, <wire kind>, <scale>, <default>)

with wire kinds U8, U16, U32, I32, F16 (2-byte, value * scale), F32 (4-byte fixed
point, value * scale), F32A (4-byte IEEE float, subnormals zeroed) and NONE for a runtime
value the reference does not serialise. The nested bms_config's fields are rows of their
own, with dotted expressions, exactly as the reference writes them.

The order is the reference's *serialisation* order, not its declaration order: those
differ, and the wire is what has to match. Runtime-only members are appended, since the
struct needs them and the wire does not.

Any statement in the reference serialiser that does not parse is a hard error, so a
reference change surfaces here rather than as a silently short byte stream.
"""

import argparse
import os
import re
import subprocess
import sys

# chibiOS-isms and the enum types declared in datatypes.h; everything else in a member
# declaration is a plain C type or a struct defined in the same header.
PLAIN_TYPES = {
    "float",
    "double",
    "int",
    "bool",
    "uint8_t",
    "int8_t",
    "uint16_t",
    "int16_t",
    "uint32_t",
    "int32_t",
}

# Types the port already declares in an app it cannot depend on. app/foc_core's
# foc_math.h owns the observer enum (same constants, same order), and apps do not
# include each other, so the generated struct carries the wire byte as uint8_t instead
# of redeclaring a colliding enum. Byte-identical on the wire, and the real fix - one
# shared types header below both apps - is recorded in docs/adr-conformance.md.
PORT_OWNED_TYPES = {"mc_foc_observer_type": "uint8_t"}

MEMBER_RE = re.compile(
    r"^([A-Za-z_][A-Za-z_0-9 *]*?)\s+([a-zA-Z_][a-zA-Z_0-9]*)(\[([0-9]+)\])?;$"
)

# reference writer call -> port wire kind
KIND_MAP = {
    "float32_auto": "F32A",
    "float16": "F16",
    "float32": "F32",
    "uint8": "U8",
    "uint16": "U16",
    "uint32": "U32",
    "int32": "I32",
}

# the shapes confgenerator_serialize_mcconf() writes in
WRITE_CAST_U8_RE = re.compile(r"^buffer\[ind\+\+\] = \(uint8_t\)conf->([a-zA-Z_0-9.\[\]]+);$")
WRITE_U8_RE = re.compile(r"^buffer\[ind\+\+\] = conf->([a-zA-Z_0-9.\[\]]+);$")
APPEND_SCALED_RE = re.compile(
    r"^buffer_append_([a-z0-9_]+)\(buffer, conf->([a-zA-Z_0-9.\[\]]+), ([\d.e-]+), &ind\);$"
)
APPEND_PLAIN_RE = re.compile(
    r"^buffer_append_([a-z0-9_]+)\(buffer, conf->([a-zA-Z_0-9.\[\]]+), &ind\);$"
)
# names may be dotted (conf->bms.type) and indexed (conf->hall_table[0])
DEFAULT_RE = re.compile(r"^conf->([a-zA-Z_0-9.\[\]]+)\s*=\s*(.+?);$")
MACRO_RE = re.compile(r"^#define\s+(MCCONF_[A-Z0-9_]+)\s+(.+?)(\s*//.*)?$")


def brace_body(text, signature):
    """Return the body of the function whose signature is `signature`."""
    start = text.index(signature)
    i = text.index("{", start)
    depth = 0
    for j in range(i, len(text)):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                return text[i + 1 : j]
    raise SystemExit(f"unbalanced braces after {signature}")


def struct_body(text, name, tail):
    """Return the body of the struct that is closed by tail (e.g. 'mc_configuration')."""
    end = text.index("} " + tail + ";")
    start = text.rindex("typedef struct", 0, end)
    i = text.index("{", start)
    # the struct members are everything up to `end`
    return text[i + 1 : end]


def to_int(text, default):
    """Parse a captured number, falling back to default rather than raising."""
    try:
        return int(text)
    except (TypeError, ValueError):
        return default


def parse_members(body):
    members = {}
    order = []
    for line in body.splitlines():
        line = line.split("//")[0].strip()
        if not line or line.startswith(("/*", "*")):
            continue
        m = MEMBER_RE.match(line)
        if not m:
            continue
        members[m.group(2)] = (m.group(1).strip(), to_int(m.group(4), 1))
        order.append(m.group(2))
    return members, order


def parse_wire(body):
    """Return [(kind, member, scale)] in wire order, plus the unparsed statements."""
    wire = []
    unparsed = []
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("int32_t ind") or line == "return ind;":
            continue
        if "MCCONF_SIGNATURE" in line:
            continue  # fixed 4-byte signature, not a member
        m = WRITE_CAST_U8_RE.match(line) or WRITE_U8_RE.match(line)
        if m:
            wire.append(("U8", m.group(1), "0"))
            continue
        m = APPEND_SCALED_RE.match(line)
        if m:
            wire.append((m.group(1), m.group(2), m.group(3)))
            continue
        m = APPEND_PLAIN_RE.match(line)
        if m:
            wire.append((m.group(1), m.group(2), "0"))
            continue
        unparsed.append(line)
    return wire, unparsed


def parse_defaults(body):
    defaults = {}
    for line in body.splitlines():
        line = line.split("//")[0].strip()
        m = DEFAULT_RE.match(line)
        if m:
            defaults[m.group(1)] = m.group(2).strip()
    return defaults


KIND_SIZE = {"U8": 1, "U16": 2, "U32": 4, "I32": 4, "F16": 2, "F32": 4, "F32A": 4, "NONE": 0}


def open_or_die(path, mode):
    """Open a file, turning a missing or unwritable path into a message."""
    try:
        return open(path, mode, encoding="utf-8")
    except OSError as exc:
        raise SystemExit(f"cannot open {path}: {exc}") from exc


def read_text(path):
    """Read a file, turning a missing tree into a message instead of a traceback."""
    with open_or_die(path, "r") as fh:
        return fh.read()


def write_text(path, text):
    with open_or_die(path, "w") as fh:
        fh.write(text)


def format_in_place(path):
    """Run clang-format over a generated header so regenerating never leaves a file the
    pre-commit hook rejects. Absent clang-format is a note, not a failure."""
    try:
        subprocess.run(["clang-format", "-i", path], check=False)
    except OSError:
        print(f"note: clang-format not found; format {path} before committing")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--reference",
        default=None,
        help="the reference tree (default: vendor/bldc, else ../bldc)",
    )
    ap.add_argument("--out", default="app/motor_config", help="the port's motor_config root")
    args = ap.parse_args()

    ref = args.reference
    if ref is None:
        for candidate in ("vendor/bldc", "../bldc"):
            if os.path.exists(os.path.join(candidate, "confgenerator.c")):
                ref = candidate
                break
        else:
            raise SystemExit("reference tree not found; pass --reference")
    datatypes = read_text(os.path.join(ref, "datatypes.h"))
    confgen = read_text(os.path.join(ref, "confgenerator.c"))
    defaults_h = read_text(os.path.join(ref, "motor", "mcconf_default.h"))
    confgenerator_h = read_text(os.path.join(ref, "confgenerator.h"))

    members, decl_order = parse_members(struct_body(datatypes, "mc_configuration", "mc_configuration"))
    bms_members, _ = parse_members(struct_body(datatypes, "bms_config", "bms_config"))
    wire, unparsed = parse_wire(brace_body(confgen, "int32_t confgenerator_serialize_mcconf"))
    defaults = parse_defaults(brace_body(confgen, "void confgenerator_set_defaults_mcconf"))

    if unparsed:
        raise SystemExit("unparsed serialiser statements:\n  " + "\n  ".join(unparsed))

    # macros used by the defaults, with the reference's line numbers as provenance
    macros = {}
    for n, line in enumerate(defaults_h.splitlines(), 1):
        m = MACRO_RE.match(line)
        if m:
            macros[m.group(1)] = (m.group(2).strip(), n)

    # Defaults that name a constant from an enum the port owns (see PORT_OWNED_TYPES) are
    # emitted as the number, with the constant kept as a comment: the port's own enum lives
    # in an app this module may not include, and the ordinal is what the wire carries.
    owned_constants = {}
    for t in PORT_OWNED_TYPES:
        idx2 = datatypes.find("} " + t + ";")
        if idx2 < 0:
            continue
        st2 = datatypes.rindex("typedef enum", 0, idx2)
        body2 = datatypes[datatypes.index("{", st2) + 1 : idx2]
        ordinal = 0
        for entry in body2.split(","):
            name = entry.split("=")[0].strip()
            if not name or not re.match(r"^[A-Z][A-Z0-9_]*$", name):
                continue
            owned_constants[name] = ordinal
            ordinal += 1

    def resolve_default(expr):
        def sub(match):
            name = match.group(0)
            if name not in owned_constants:
                return name
            return f"{owned_constants[name]} /* {name} */"

        return re.sub(r"\bFOC_[A-Z0-9_]+\b", sub, expr)

    rows = []
    wire_members = set()
    for kind, expr, scale in wire:
        member = expr.split("[")[0].split(".")[0]
        if member not in members:
            raise SystemExit(f"wire member {expr} is not a mc_configuration member")
        wire_members.add(member)
        rows.append((KIND_MAP.get(kind, kind), expr, scale, resolve_default(defaults.get(expr, "0"))))
    for name in decl_order:
        if name in wire_members:
            continue
        rows.append(("NONE", name, "0", resolve_default(defaults.get(name, "0"))))

    # the wire length this manifest implies; the static assert in the header pins 484
    wire_len = 4  # the signature
    for kind, expr, _, _ in rows:
        if kind not in KIND_SIZE:
            raise SystemExit(f"unknown wire kind {kind} for {expr}")
        wire_len += KIND_SIZE[kind]

    enums = sorted(
        {
            t
            for t, _ in members.values()
            if t not in PLAIN_TYPES and t != "bms_config" and t not in PORT_OWNED_TYPES
        }
    )
    enums += ["BMS_TYPE", "BMS_FWD_CAN_MODE"]
    enum_blocks = []
    for t in sorted(set(enums)):
        idx = datatypes.find("} " + t + ";")
        if idx < 0:
            raise SystemExit(f"enum {t} not found in datatypes.h")
        st = datatypes.rindex("typedef enum", 0, idx)
        enum_blocks.append(datatypes[st : idx + len("} ") + len(t) + 1].strip())

    bms_block = None
    idx = datatypes.index("} bms_config;")
    st = datatypes.rindex("typedef struct", 0, idx)
    bms_block = datatypes[st : idx + len("} ") + len("bms_config") + 1].strip()

    stamp = (
        "/*\n"
        " * GENERATED by tools/gen_mcconf_from_reference.py - do not edit by hand.\n"
        f" * Source of truth: {ref}/datatypes.h,\n"
        f" *                  {ref}/confgenerator.c,\n"
        f" *                  {ref}/motor/mcconf_default.h\n"
        " */\n"
    )

    # 1. enums + bms_config
    enum_path = os.path.join(args.out, "include", "motor_config", "mcconf_enums.h")
    enum_text = stamp + "\n#ifndef MCCONF_ENUMS_H\n#define MCCONF_ENUMS_H\n\n#include <stdbool.h>\n#include <stdint.h>\n\n"
    enum_text += "\n\n".join(enum_blocks)
    enum_text += "\n\n" + bms_block + "\n\n#endif /* MCCONF_ENUMS_H */\n"
    write_text(enum_path, enum_text)

    # 2. the manifest
    manifest_path = os.path.join(args.out, "include", "motor_config", "mcconf_manifest.h")
    with open_or_die(manifest_path, "w") as f:
        f.write(stamp)
        f.write(
            "\n/*\n"
            " * One row per byte-stream item, in the reference's own order, array elements\n"
            " * included (the reference writes hall_table[0]..[7] one at a time, and gives\n"
            " * each its own MCCONF_HALL_TAB_n default):\n"
            " *\n"
            " *   X(<wire kind>, <expression>, <scale>, <default>)\n"
            " *\n"
            " * Kinds: U8/U16/U32/I32 integers, F16 (2 bytes, value * scale), F32 (4 bytes,\n"
            " * fixed point, value * scale), F32A (4 bytes, IEEE float, subnormals zeroed),\n"
            " * BMS rows are the nested bms_config's own fields, written by the reference\n"
            " * one at a time; NONE marks a runtime value the reference does not serialise.\n"
            " *\n"
            " * The same list drives the writer, the reader and the defaults, so those three\n"
            " * cannot disagree; and MCCONF_WIRE_LEN is asserted to be the reference's 488.\n"
            " */\n\n"
        )
        f.write("#ifndef MCCONF_MANIFEST_H\n#define MCCONF_MANIFEST_H\n\n")
        sig = re.search(r"#define\s+(MCCONF_SIGNATURE|APPCONF_SIGNATURE)\s+(\d+)", confgenerator_h)
        if not sig:
            raise SystemExit("no MCCONF_SIGNATURE in confgenerator.h")
        f.write("/* confgenerator.h: the signature the stream starts with. */\n")
        for m in re.finditer(r"#define\s+(MCCONF_SIGNATURE|APPCONF_SIGNATURE)\s+(\d+)", confgenerator_h):
            f.write(f"#define {m.group(1)} {m.group(2)}u\n")
        f.write("\n#define MCCONF_WIRE(X) \\\n")
        for i, (kind, expr, scale, default) in enumerate(rows):
            f.write(f"    X({kind}, {expr}, {scale}, {default})" + (" \\\n" if i + 1 < len(rows) else "\n"))
        f.write("\n#define MCCONF_KIND_LEN_U8 1\n")
        f.write("#define MCCONF_KIND_LEN_U16 2\n")
        f.write("#define MCCONF_KIND_LEN_U32 4\n")
        f.write("#define MCCONF_KIND_LEN_I32 4\n")
        f.write("#define MCCONF_KIND_LEN_F16 2\n")
        f.write("#define MCCONF_KIND_LEN_F32 4\n")
        f.write("#define MCCONF_KIND_LEN_F32A 4\n")
        f.write("#define MCCONF_KIND_LEN_NONE 0\n")
        f.write("#define MCCONF_WIRE_LEN_ONE(kind, expr, scale, def) + MCCONF_KIND_LEN_##kind\n")
        f.write("#define MCCONF_WIRE_LEN (4 MCCONF_WIRE(MCCONF_WIRE_LEN_ONE))\n")
        f.write("\n#endif /* MCCONF_MANIFEST_H */\n")

    # 3. the defaults macros, in the reference's own spelling
    used = set()
    for _, _, _, default in rows:
        used |= set(re.findall(r"MCCONF_[A-Z0-9_]+", default))
    defaults_path = os.path.join(args.out, "src", "mcconf_defaults.h")
    with open_or_die(defaults_path, "w") as f:
        f.write(stamp)
        f.write(
            "\n/*\n"
            " * Only the macros the manifest's defaults use, with the reference's own line\n"
            f" * number in {ref}/motor/mcconf_default.h so each value can be checked there.\n"
            " */\n\n"
            "#ifndef MCCONF_DEFAULTS_H\n#define MCCONF_DEFAULTS_H\n\n"
        )
        missing = []
        for name in sorted(used):
            if name not in macros:
                missing.append(name)
                continue
            value, line = macros[name]
            f.write(f"/* mcconf_default.h:{line} */\n#define {name} {resolve_default(value)}\n")
        f.write("\n#endif /* MCCONF_DEFAULTS_H */\n")
    if missing:
        raise SystemExit("defaults without a reference macro: " + ", ".join(missing))

    # 4. the struct itself. It cannot come from MCCONF_FIELDS(X): a row knows its array
    # size as a number, and a macro cannot turn 1 into "no brackets". The declaration
    # order is the reference's datatypes.h order here, not the wire order, and nothing
    # observable depends on it - the manifest is what the wire follows.
    struct_path = os.path.join(args.out, "include", "motor_config", "mcconf_struct.h")
    struct_text = stamp
    struct_text += (
        "\n/*\n"
        " * mc_configuration_t, generated from the reference's datatypes.h so the port cannot\n"
        " * drift from it field by field. Member order follows datatypes.h; the *wire* order\n"
        " * is the one in mcconf_manifest.h, and they differ.\n"
        " */\n\n"
        "#ifndef MCCONF_STRUCT_H\n#define MCCONF_STRUCT_H\n\n"
        '#include "motor_config/mcconf_enums.h"\n\n'
        "typedef struct {\n"
    )
    for name in decl_order:
        ctype, size = members[name]
        ctype = PORT_OWNED_TYPES.get(ctype, ctype)
        suffix = f"[{size}]" if size > 1 else ""
        struct_text += f"    {ctype} {name}{suffix};\n"
    struct_text += "} mc_configuration_t;\n\n#endif /* MCCONF_STRUCT_H */\n"
    write_text(struct_path, struct_text)

    print(f"members={len(members)} wire items={len(wire)} rows={len(rows)}")
    print(f"enums={len(enum_blocks)} rows={len(rows)} defaults macros={len(used)}")
    print(f"computed wire length={wire_len} (the reference's is 488)")
    for path in (enum_path, manifest_path, defaults_path, struct_path):
        format_in_place(path)
    return 0 if wire_len == 488 else 1


if __name__ == "__main__":
    sys.exit(main())
