#!/usr/bin/env python3
"""Generate the HFI excitation tables from the reference tree.

The four tables in util/utils_math.c hold *rounded* six-decimal cosines and sines of a 32 point
grid - 0.980785 rather than the 0.98078531 that cosf(pi/16) gives - so they are extracted rather
than recomputed. Recomputing them would move HFI's angle error a little every cycle, which is
exactly the kind of difference this migration is meant to exclude.

Same method as tools/gen_mcconf_from_reference.py: read the reference, emit the header, and refuse
to write anything when a statement does not parse into the shape that was expected.

Usage: python3 tools/gen_hfi_from_reference.py [--check]

--check regenerates and compares against the file on disk without writing it, which is what CI
would run.
"""

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REFERENCE = REPO.parent / "bldc" / "util" / "utils_math.c"
OUTPUT = REPO / "app" / "foc_core" / "src" / "hfi_tables.h"

TABLES = [
    ("utils_tab_cos_32_1", "float"),
    ("utils_tab_sin_32_1", "float"),
    ("utils_tab_cos_32_2", "float"),
    ("utils_tab_sin_32_2", "float"),
]


def extract(source: str, name: str) -> list[str]:
    """Pull one table's literals out of the reference, keeping their exact text."""
    match = re.search(
        r"const float\s+%s\[\]\s*=\s*\{([^}]*)\}" % re.escape(name), source
    )
    if match is None:
        raise SystemExit("table %s not found in %s" % (name, REFERENCE))

    values = [v.strip() for v in match.group(1).split(",") if v.strip()]
    if len(values) != 32:
        raise SystemExit("table %s has %d entries, expected 32" % (name, len(values)))
    for value in values:
        if not re.fullmatch(r"-?\d+\.\d+", value):
            raise SystemExit("table %s holds %r, which is not a six-decimal literal" % (name, value))
    return values


def rows(values: list[str]) -> str:
    """Eight per line, as the reference writes them."""
    lines = []
    for i in range(0, len(values), 8):
        lines.append("    " + ", ".join(values[i : i + 8]) + ",")
    return "\n".join(lines)


def generate() -> str:
    if not REFERENCE.is_file():
        raise SystemExit("reference tree not found at %s" % REFERENCE)
    source = REFERENCE.read_text()

    body = []
    for name, kind in TABLES:
        values = extract(source, name)
        body.append(
            "/* vendor/bldc/util/utils_math.c: const float %s[] */\nconst %s foc_%s[] = {\n%s\n};"
            % (name, kind, name, rows(values))
        )

    header = """/*
 * HFI's excitation tables, generated by tools/gen_hfi_from_reference.py from the reference's
 * util/utils_math.c. Do not edit: change the generator or the reference.
 *
 * They are rounded six-decimal cosines and sines, not what cosf/sinf produce, so they are
 * extracted rather than recomputed - HFI's angle error is computed from these numbers every
 * cycle, and a last-digit difference there would accumulate.
 *
 * They live in the app because an app may not depend on infra (D30), the same reason vesc_can and
 * motor_config each carry their own crc16.
 */
#ifndef APP_FOC_CORE_HFI_TABLES_H
#define APP_FOC_CORE_HFI_TABLES_H

%s

#endif /* APP_FOC_CORE_HFI_TABLES_H */
""" % "\n\n".join(body)

    return header


def main() -> int:
    generated = generate()
    formatted = subprocess.run(
        ["clang-format"], input=generated, capture_output=True, text=True
    )
    if formatted.returncode == 0:
        generated = formatted.stdout

    if "--check" in sys.argv:
        if not OUTPUT.is_file():
            print("%s does not exist; run the generator" % OUTPUT)
            return 1
        if OUTPUT.read_text() != generated:
            print("%s is stale; run the generator" % OUTPUT)
            return 1
        print("%s is up to date" % OUTPUT)
        return 0

    OUTPUT.write_text(generated)
    print("wrote %s (%d tables)" % (OUTPUT, len(TABLES)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
