#!/usr/bin/env python3
"""Generate the configuration layouts, wire manifests and defaults from the reference.

The reference's own confgenerator.c is autogenerated by VESC Tool, so the port does what
the reference does: one checked-in generator, re-runnable when the reference moves,
instead of a hand-transcribed table that silently rots.

Inputs (the reference tree, `vendor/bldc` or `../bldc`):
  datatypes.h              - every enum body and struct body
  confgenerator.c          - serialize_<x>() gives the wire order, kind and scale per
                             field, set_defaults_<x>() gives every default
  motor/mcconf_default.h   - the MCCONF_* macros the mc defaults are written in terms of
  confgenerator.h          - the stream signatures

Outputs, all stamped "generated":
  include/motor_config/vesc_enums.h        every enum the configs use
  include/motor_config/vesc_structs.h      the nested structs (bms_config, ppm_config, ...)
  include/motor_config/config_structs.h    mc_configuration_t and app_configuration_t
  include/motor_config/<base>_manifest.h   <BASE>_WIRE(X), one row per byte-stream item:
                                               X(<wire kind>, <expr>, <scale>, <default>)
  src/<base>_defaults.h                    the reference's default macros, with lines

Kinds: U8/U16/U32/I32 integers, F16 (2 bytes, value * scale), F32 (4 bytes, fixed point,
value * scale), F32A (4 bytes, IEEE float, subnormals zeroed) and NONE for a runtime
value the reference does not serialise. Nested structs appear as dotted rows, array
elements as indexed rows - exactly as the reference writes them, one statement at a
time, because it gives each element its own default macro.

Any statement in a reference serialiser that does not parse is a hard error, so a
reference change surfaces here rather than as a silently short byte stream. The stream
lengths this implies are checked against the measured ones at the end.
"""

import argparse
import os
import re
import subprocess
import sys

# Types the port already declares in an app it cannot depend on, mapped to the type to use
# instead. app/foc_core's foc_math.h owns the observer enum (same constants, same order)
# and apps do not include each other, so the generated struct carries the wire byte as
# uint8_t; the real fix, one shared types header below both apps, is recorded in
# docs/adr-conformance.md.
PORT_OWNED_TYPES = {"mc_foc_observer_type": "uint8_t"}

PLAIN_TYPES = {
    "float",
    "double",
    "int",
    "bool",
    "uint8_t",
    "int8_t",
    "uint16_t",
    "int16_t",
    "uint32_t",
    "int32_t",
}

# reference writer call -> port wire kind
KIND_MAP = {
    "float32_auto": "F32A",
    "float16": "F16",
    "float32": "F32",
    "uint8": "U8",
    "uint16": "U16",
    "uint32": "U32",
    "int32": "I32",
}
KIND_SIZE = {"U8": 1, "U16": 2, "U32": 4, "I32": 4, "F16": 2, "F32": 4, "F32A": 4, "NONE": 0}

MEMBER_RE = re.compile(
    r"^([A-Za-z_][A-Za-z_0-9 *]*?)\s+([a-zA-Z_][a-zA-Z_0-9]*)(\[([0-9]+)\])?;$"
)
# names may be dotted (conf->bms.type) and indexed (conf->hall_table[0])
WRITE_CAST_U8_RE = re.compile(r"^buffer\[ind\+\+\] = \(uint8_t\)conf->([a-zA-Z_0-9.\[\]]+);$")
WRITE_U8_RE = re.compile(r"^buffer\[ind\+\+\] = conf->([a-zA-Z_0-9.\[\]]+);$")
APPEND_SCALED_RE = re.compile(
    r"^buffer_append_([a-z0-9_]+)\(buffer, conf->([a-zA-Z_0-9.\[\]]+), ([\d.e-]+), &ind\);$"
)
APPEND_PLAIN_RE = re.compile(
    r"^buffer_append_([a-z0-9_]+)\(buffer, conf->([a-zA-Z_0-9.\[\]]+), &ind\);$"
)
DEFAULT_RE = re.compile(r"^conf->([a-zA-Z_0-9.\[\]]+)\s*=\s*(.+?);$")
MACRO_RE = re.compile(r"^#define\s+([A-Z][A-Z0-9_]+)\s+(.+?)(\s*//.*)?$")

# One entry per configuration stream. `expected_len` is the length measured from the
# reference's own serialiser with the harness recorded in docs/bldc-mcconf-format.md.
STREAMS = [
    {
        "base": "mcconf",
        "root": "mc_configuration",
        "root_type": "mc_configuration_t",
        "serialize": "int32_t confgenerator_serialize_mcconf",
        "defaults": "void confgenerator_set_defaults_mcconf",
        "defaults_header": "motor/mcconf_default.h",
        "expected_len": 488,
    },
    {
        "base": "appconf",
        "root": "app_configuration",
        "root_type": "app_configuration_t",
        "serialize": "int32_t confgenerator_serialize_appconf",
        "defaults": "void confgenerator_set_defaults_appconf",
        "defaults_header": "applications/appconf_default.h",
        "expected_len": 290,
    },
]


def open_or_die(path, mode):
    """Open a file, turning a missing or unwritable path into a message."""
    try:
        return open(path, mode, encoding="utf-8")
    except OSError as exc:
        raise SystemExit(f"cannot open {path}: {exc}") from exc


def read_text(path):
    """Read a file, turning a missing tree into a message instead of a traceback."""
    with open_or_die(path, "r") as fh:
        return fh.read()


def write_text(path, text):
    with open_or_die(path, "w") as fh:
        fh.write(text)


def format_in_place(path):
    """Run clang-format over a generated header so regenerating never leaves a file the
    pre-commit hook rejects. Absent clang-format is a note, not a failure."""
    try:
        subprocess.run(["clang-format", "-i", path], check=False)
    except OSError:
        print(f"note: clang-format not found; format {path} before committing")


def to_int(text, default):
    """Parse a captured number, falling back to default rather than raising."""
    try:
        return int(text)
    except (TypeError, ValueError):
        return default


def body_after(text, signature):
    """The body of the function whose signature is `signature`."""
    start = text.index(signature)
    i = text.index("{", start)
    depth = 0
    for j in range(i, len(text)):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                return text[i + 1 : j]
    raise SystemExit(f"unbalanced braces after {signature}")


def body_of_type(text, tail, keyword):
    """The body of the enum/struct closed by `} tail;`."""
    end = text.index("} " + tail + ";")
    start = text.rindex(keyword, 0, end)
    return text[text.index("{", start) + 1 : end], text[start : end + len(tail) + 3]


def parse_members(body):
    """{name: (c type, array size)} plus the declaration order."""
    members = {}
    order = []
    for line in body.splitlines():
        line = line.split("//")[0].strip()
        if not line or line.startswith(("/*", "*")):
            continue
        m = MEMBER_RE.match(line)
        if not m:
            continue
        members[m.group(2)] = (m.group(1).strip(), to_int(m.group(4), 1))
        order.append(m.group(2))
    return members, order


def parse_wire(body):
    """[(kind, expression, scale)] in wire order, plus any unparsed statements."""
    wire = []
    unparsed = []
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("int32_t ind") or line == "return ind;":
            continue
        if "SIGNATURE" in line:
            continue  # the fixed 4-byte signature, not a member
        m = WRITE_CAST_U8_RE.match(line) or WRITE_U8_RE.match(line)
        if m:
            wire.append(("U8", m.group(1), "0"))
            continue
        m = APPEND_SCALED_RE.match(line)
        if m:
            wire.append((m.group(1), m.group(2), m.group(3)))
            continue
        m = APPEND_PLAIN_RE.match(line)
        if m:
            wire.append((m.group(1), m.group(2), "0"))
            continue
        unparsed.append(line)
    return wire, unparsed


def parse_defaults(body):
    defaults = {}
    for line in body.splitlines():
        line = line.split("//")[0].strip()
        m = DEFAULT_RE.match(line)
        if m:
            defaults[m.group(1)] = m.group(2).strip()
    return defaults


def collect_types(datatypes, structs, enums, root, seen=None):
    """Every struct and enum reachable from `root`, so the generated headers declare
    exactly what the configuration needs - bms_config, ppm_config and friends included."""
    if seen is None:
        seen = set()
    if root in seen:
        return seen
    seen.add(root)
    body = structs[root][0] if root in structs else enums[root]
    for line in body.splitlines():
        line = line.split("//")[0].strip()
        if not line or line.startswith(("/*", "*")):
            continue
        m = MEMBER_RE.match(line)
        if not m:
            continue
        ctype = m.group(1).strip()
        if ctype in structs:
            collect_types(datatypes, structs, enums, ctype, seen)
        elif ctype not in PLAIN_TYPES and ctype in enums:
            seen.add(ctype)
    return seen


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--reference",
        default=None,
        help="the reference tree (default: vendor/bldc, else ../bldc)",
    )
    ap.add_argument("--out", default="app/motor_config", help="the port's motor_config root")
    args = ap.parse_args()

    ref = args.reference
    if ref is None:
        for candidate in ("vendor/bldc", "../bldc"):
            if os.path.exists(os.path.join(candidate, "confgenerator.c")):
                ref = candidate
                break
        else:
            raise SystemExit("reference tree not found; pass --reference")

    datatypes = read_text(os.path.join(ref, "datatypes.h"))
    confgen = read_text(os.path.join(ref, "confgenerator.c"))
    confgenerator_h = read_text(os.path.join(ref, "confgenerator.h"))

    # every enum and struct body in datatypes.h, by name
    enums = {}
    for m in re.finditer(r"typedef enum\b", datatypes):
        start = m.start()
        name_m = re.compile(r"\}\s*([A-Za-z_][A-Za-z_0-9]*)\s*;").match(datatypes, datatypes.index("}", start))
        if not name_m:
            continue
        name = name_m.group(1)
        tail = datatypes[start : name_m.end()]
        enums[name] = tail[tail.index("{") + 1 : tail.rindex("}")]
    structs = {}
    for m in re.finditer(r"typedef struct\b", datatypes):
        start = m.start()
        end = datatypes.index("} ", start)
        semi = datatypes.index(";", end)
        name = datatypes[end + 2 : semi].strip()
        if not re.match(r"^[A-Za-z_][A-Za-z_0-9]*$", name):
            continue
        structs[name] = (datatypes[datatypes.index("{", start) + 1 : end], datatypes[start : semi + 1])

    owned_constants = {}
    for t in PORT_OWNED_TYPES:
        ordinal = 0
        for entry in enums.get(t, "").split(","):
            name = entry.split("=")[0].strip()
            if not name or not re.match(r"^[A-Z][A-Z0-9_]*$", name):
                continue
            owned_constants[name] = ordinal
            ordinal += 1

    def resolve_default(expr):
        def sub(match):
            name = match.group(0)
            if name not in owned_constants:
                return name
            return f"{owned_constants[name]} /* {name} */"

        return re.sub(r"\bFOC_[A-Z0-9_]+\b", sub, expr)

    stamp = (
        "/*\n"
        " * GENERATED by tools/gen_mcconf_from_reference.py - do not edit by hand.\n"
        f" * Source of truth: {ref}/datatypes.h,\n"
        f" *                  {ref}/confgenerator.c,\n"
        f" *                  {ref}/motor/mcconf_default.h\n"
        " */\n"
    )

    out_include = os.path.join(args.out, "include", "motor_config")
    out_src = os.path.join(args.out, "src")
    needed_structs = set()
    needed_enums = set()
    written = []
    status = 0

    for stream in STREAMS:
        base = stream["base"]
        members, decl_order = parse_members(structs[stream["root"]][0])
        wire, unparsed = parse_wire(body_after(confgen, stream["serialize"]))
        defaults = parse_defaults(body_after(confgen, stream["defaults"]))
        if unparsed:
            raise SystemExit(
                f"unparsed {base} serialiser statements:\n  " + "\n  ".join(unparsed)
            )

        defaults_h = read_text(os.path.join(ref, stream["defaults_header"]))
        macros = {}
        for n, line in enumerate(defaults_h.splitlines(), 1):
            m = MACRO_RE.match(line)
            if m and m.group(1) != "INCLUDE_GUARD":
                macros[m.group(1)] = (m.group(2).strip(), n)

        rows = []
        wire_members = set()
        for kind, expr, scale in wire:
            member = expr.split("[")[0].split(".")[0]
            if member not in members:
                raise SystemExit(f"{base}: wire member {expr} is not a {stream['root']} member")
            wire_members.add(member)
            rows.append(
                (KIND_MAP.get(kind, kind), expr, scale, resolve_default(defaults.get(expr, "0")))
            )
        for name in decl_order:
            if name in wire_members:
                continue
            rows.append(("NONE", name, "0", resolve_default(defaults.get(name, "0"))))

        wire_len = 4  # the signature
        for kind, expr, _, _ in rows:
            if kind not in KIND_SIZE:
                raise SystemExit(f"{base}: unknown wire kind {kind} for {expr}")
            wire_len += KIND_SIZE[kind]

        # defaults macros, with provenance
        used = set()
        for _, _, _, default in rows:
            used |= set(re.findall(r"\b[A-Z][A-Z0-9_]{2,}\b", default))
        used = {u for u in used if u in macros}
        missing = []
        for name in sorted(used):
            if name not in macros:
                missing.append(name)
        defaults_text = stamp + (
            "\n/*\n"
            " * The macros this stream's defaults are written in terms of, with the\n"
            f" * reference's line number in {ref}/{stream['defaults_header']} so each\n"
            " * value can be checked there.\n"
            " */\n\n"
        )
        defaults_text += f"#ifndef {base.upper()}_DEFAULTS_H\n#define {base.upper()}_DEFAULTS_H\n\n"
        for name in sorted(used):
            value, line = macros[name]
            defaults_text += f"/* {stream['defaults_header']}:{line} */\n#define {name} {resolve_default(value)}\n"
        # Defaults may lean on a board macro the reference takes from the hwconf. This
        # module has no board wired into it, so the reference's usual value stands in and
        # the product can override it; without this the generated manifest would not
        # compile at all.
        board_macros = {
            m
            for _, _, _, default in rows
            for m in re.findall(r"\bHW_[A-Z0-9_]+\b", default)
        }
        for name in sorted(board_macros):
            defaults_text += (
                f"/* the reference takes {name} from the board's hwconf */\n"
                f"#ifndef {name}\n#define {name} 1\n#endif\n"
            )
        defaults_text += f"\n#endif /* {base.upper()}_DEFAULTS_H */\n"
        defaults_path = os.path.join(out_src, f"{base}_defaults.h")
        write_text(defaults_path, defaults_text)
        written.append(defaults_path)

        # the manifest
        manifest = stamp + (
            "\n/*\n"
            " * One row per byte-stream item, in the reference's own order: array elements and\n"
            " * nested struct fields are rows of their own, exactly as the reference writes\n"
            " * them.\n"
            " *\n"
            " *   X(<wire kind>, <expression>, <scale>, <default>)\n"
            " *\n"
            " * Kinds: U8/U16/U32/I32 integers, F16 (2 bytes, value * scale), F32 (4 bytes,\n"
            " * fixed point, value * scale), F32A (4 bytes, IEEE float, subnormals zeroed),\n"
            " * NONE for a runtime value the reference does not serialise.\n"
            " *\n"
            " * The same list drives the writer, the reader and the defaults, so those three\n"
            f" * cannot disagree, and {base.upper()}_WIRE_LEN is asserted to be the reference's\n"
            f" * {stream['expected_len']} bytes.\n"
            " */\n\n"
        )
        manifest += f"#ifndef {base.upper()}_MANIFEST_H\n#define {base.upper()}_MANIFEST_H\n\n"
        for m in re.finditer(r"#define\s+([A-Z]+_SIGNATURE)\s+(\d+)", confgenerator_h):
            if m.group(1) != f"{base.upper()}_SIGNATURE":
                continue
            manifest += "/* confgenerator.h: the signature this stream starts with. */\n"
            manifest += f"#define {m.group(1)} {m.group(2)}u\n"
        manifest += f"\n#define {base.upper()}_WIRE(X) \\\n"
        for i, (kind, expr, scale, default) in enumerate(rows):
            line = f"    X({kind}, {expr}, {scale}, {default})"
            manifest += line + (" \\\n" if i + 1 < len(rows) else "\n")
        manifest += "\n".join(
            f"#define {base.upper()}_KIND_LEN_{k} {v}" for k, v in KIND_SIZE.items()
        )
        manifest += "\n"
        manifest += (
            f"#define {base.upper()}_WIRE_LEN_ONE(kind, expr, scale, def)"
            f" + {base.upper()}_KIND_LEN_##kind\n"
        )
        manifest += (
            f"#define {base.upper()}_WIRE_LEN (4 {base.upper()}_WIRE(MCCONF_WIRE_LEN_PLACEHOLDER))\n"
        )
        manifest = manifest.replace(
            f"{base.upper()}_WIRE(MCCONF_WIRE_LEN_PLACEHOLDER)",
            f"{base.upper()}_WIRE({base.upper()}_WIRE_LEN_ONE)",
        )
        manifest += f"\n#endif /* {base.upper()}_MANIFEST_H */\n"
        manifest_path = os.path.join(out_include, f"{base}_manifest.h")
        write_text(manifest_path, manifest)
        written.append(manifest_path)

        for t in collect_types(datatypes, structs, enums, stream["root"]):
            if t in structs:
                needed_structs.add(t)
            elif t in enums:
                needed_enums.add(t)

        print(
            f"{base}: members={len(members)} wire items={len(wire)} rows={len(rows)} "
            f"length={wire_len} (reference: {stream['expected_len']})"
        )
        if wire_len != stream["expected_len"]:
            print(f"  ERROR: {base} length differs from the reference's")
            status = 1

    # shared type headers
    enum_text = stamp + "\n#ifndef VESC_ENUMS_H\n#define VESC_ENUMS_H\n\n#include <stdbool.h>\n#include <stdint.h>\n\n"
    for name in sorted(needed_enums):
        if name in PORT_OWNED_TYPES:
            # The port's own app declares these constants; only the wire byte matters here,
            # and the defaults that name them are resolved to their ordinals.
            continue
        enum_text += f"typedef enum {{{enums[name]}}} {name};\n\n"
    enum_text += "\n#endif /* VESC_ENUMS_H */\n"
    enums_path = os.path.join(out_include, "vesc_enums.h")
    write_text(enums_path, enum_text)
    written.append(enums_path)

    # structs in dependency order: a struct's member types come before it
    ordered = []
    pending = sorted(needed_structs)
    while pending:
        progressed = False
        for name in list(pending):
            deps = {t for t, _ in parse_members(structs[name][0])[0].values()}
            if not (deps & set(pending)) - {name}:
                ordered.append(name)
                pending.remove(name)
                progressed = True
        if not progressed:
            raise SystemExit("struct dependency cycle: " + ", ".join(pending))
    struct_text = stamp + "\n#ifndef VESC_STRUCTS_H\n#define VESC_STRUCTS_H\n\n"
    struct_text += '#include "motor_config/vesc_enums.h"\n\n'
    for name in ordered:
        if name in STREAMS_BY_ROOT:
            continue  # the roots are declared in config_structs.h
        body = structs[name][1].strip()
        body = re.sub(r"\}\s*" + name + r";", f"}} {name};", body)
        struct_text += body + "\n\n"
    struct_text += "\n#endif /* VESC_STRUCTS_H */\n"
    structs_path = os.path.join(out_include, "vesc_structs.h")
    write_text(structs_path, struct_text)
    written.append(structs_path)

    config_text = stamp + "\n#ifndef CONFIG_STRUCTS_H\n#define CONFIG_STRUCTS_H\n\n"
    config_text += '#include "motor_config/vesc_structs.h"\n\n'
    for stream in STREAMS:
        body = structs[stream["root"]][1].strip()
        for owned, replacement in PORT_OWNED_TYPES.items():
            body = re.sub(r"\b" + owned + r"\b", replacement, body)
        body = re.sub(r"\}\s*" + stream["root"] + r";", f"}} {stream['root_type']};", body)
        config_text += body + "\n\n"
    config_text += "\n#endif /* CONFIG_STRUCTS_H */\n"
    config_path = os.path.join(out_include, "config_structs.h")
    write_text(config_path, config_text)
    written.append(config_path)

    for path in written:
        format_in_place(path)
    return status


STREAMS_BY_ROOT = {s["root"] for s in STREAMS}

if __name__ == "__main__":
    sys.exit(main())
