#include "edge/module.h"
#include <string.h>
static int valid(const edge_module_descriptor_t *d){return d&&d->preamble&&edge_module_validate_preamble(d->preamble)==EDGE_OK;}
int edge_module_validate_preamble(const edge_module_preamble_v1_t*p){if(!p)return EDGE_EINVAL;if(p->magic!=EDGE_MODULE_MAGIC||p->abi_major!=EDGE_MODULE_ABI_MAJOR||p->preamble_size<0x60)return EDGE_EABI;return EDGE_OK;}
int edge_module_manager_init(edge_module_manager_t*m,edge_module_descriptor_t*i,uint8_t*s,size_t n,const edge_module_descriptor_t**r,size_t rn){if(!m||!i||!s||!n)return EDGE_EINVAL;memset(m,0,sizeof(*m));m->instances=i;m->started=s;m->count=n;m->registry=r;m->registry_count=rn;for(size_t x=0;x<n;x++){if(!valid(&i[x]))return EDGE_EABI;if(!i[x].ctx)return EDGE_EINVAL;i[x].ctx->preamble=i[x].preamble;i[x].ctx->instance_id=i[x].instance_id;i[x].ctx->state=EDGE_MODULE_CREATED;s[x]=0;}return EDGE_OK;}
const edge_module_descriptor_t*edge_module_find(const edge_module_manager_t*m,uint32_t id){if(!m)return 0;for(size_t i=0;i<m->count;i++)if(m->instances[i].instance_id==id)return &m->instances[i];return 0;}
static int init_one(edge_module_manager_t*m,size_t i){edge_module_descriptor_t*d=&m->instances[i];if(d->ctx->state!=EDGE_MODULE_CREATED)return EDGE_ESTATE;if(d->init){int rc=d->init(d->ctx);if(rc){d->ctx->state=EDGE_MODULE_FAILED;return rc;}}d->ctx->state=EDGE_MODULE_INITIALIZED;m->started[i]=1;return EDGE_OK;}
int edge_module_init_all(edge_module_manager_t*m){if(!m)return EDGE_EINVAL;for(size_t i=0;i<m->count;i++){int rc=init_one(m,i);if(rc){for(size_t j=i;j>0;j--){size_t k=j-1;if(m->started[k]&&m->instances[k].deinit)m->instances[k].deinit(m->instances[k].ctx);m->instances[k].ctx->state=EDGE_MODULE_STOPPED;m->started[k]=0;}return rc;}}return EDGE_OK;}
int edge_module_power_on_all(edge_module_manager_t*m){if(!m)return EDGE_EINVAL;for(size_t i=0;i<m->count;i++){if(m->instances[i].ctx->state!=EDGE_MODULE_INITIALIZED)return EDGE_ESTATE;if(m->instances[i].power_on){int rc=m->instances[i].power_on(m->instances[i].ctx);if(rc){m->instances[i].ctx->state=EDGE_MODULE_FAILED;for(size_t j=i;j>0;j--){size_t k=j-1;if(m->instances[k].ctx->state==EDGE_MODULE_RUNNING&&m->instances[k].power_off)m->instances[k].power_off(m->instances[k].ctx);m->instances[k].ctx->state=EDGE_MODULE_STOPPED;}return rc;}}m->instances[i].ctx->state=EDGE_MODULE_RUNNING;}return EDGE_OK;}
int edge_module_poll_all(edge_module_manager_t*m){if(!m)return EDGE_EINVAL;for(size_t i=0;i<m->count;i++){edge_module_descriptor_t*d=&m->instances[i];if(d->ctx->state==EDGE_MODULE_RUNNING&&d->poll){int rc=d->poll(d->ctx);if(rc<0){d->ctx->state=EDGE_MODULE_FAILED;return rc;}}}return EDGE_OK;}
int edge_module_power_off_all(edge_module_manager_t*m){if(!m)return EDGE_EINVAL;for(size_t i=m->count;i>0;i--){edge_module_descriptor_t*d=&m->instances[i-1];if(d->ctx->state==EDGE_MODULE_RUNNING||d->ctx->state==EDGE_MODULE_SUSPENDED){if(d->power_off){int rc=d->power_off(d->ctx);if(rc<0)return rc;}d->ctx->state=EDGE_MODULE_STOPPED;}}return EDGE_OK;}
int edge_module_deinit_all(edge_module_manager_t*m){if(!m)return EDGE_EINVAL;for(size_t i=m->count;i>0;i--){edge_module_descriptor_t*d=&m->instances[i-1];if(d->ctx->state!=EDGE_MODULE_STOPPED&&d->ctx->state!=EDGE_MODULE_FAILED)continue;if(d->deinit){int rc=d->deinit(d->ctx);if(rc<0)return rc;}d->ctx->state=EDGE_MODULE_CREATED;m->started[i-1]=0;}return EDGE_OK;}
int edge_module_suspend_all(edge_module_manager_t*m){if(!m)return EDGE_EINVAL;for(size_t i=m->count;i>0;i--){edge_module_descriptor_t*d=&m->instances[i-1];if(d->ctx->state==EDGE_MODULE_RUNNING&&d->suspend){int rc=d->suspend(d->ctx);if(rc<0)return rc;d->ctx->state=EDGE_MODULE_SUSPENDED;}}return EDGE_OK;}
int edge_module_resume_all(edge_module_manager_t*m){if(!m)return EDGE_EINVAL;for(size_t i=0;i<m->count;i++){edge_module_descriptor_t*d=&m->instances[i];if(d->ctx->state==EDGE_MODULE_SUSPENDED&&d->resume){int rc=d->resume(d->ctx);if(rc<0)return rc;d->ctx->state=EDGE_MODULE_RUNNING;}}return EDGE_OK;}
